// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    BudgetSnapshot,
    QueryBudget,
    QueryMeta,
    QueryProfile,
    QueryResult
} from "./models.js";

import * as $models from "./models.js";

/**
 * Row is the fundamental data unit in OQL — a map of field names to values.
 * @typedef {$models.Row} Row
 */
