// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * @readonly
 * @enum {string}
 */
export const ApprovalStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusApproved: "approved",
    StatusRejected: "rejected",
    StatusExpired: "expired",
};

/**
 * FIDO2Challenge represents an authentication challenge
 */
export class FIDO2Challenge {
    /**
     * Creates a new FIDO2Challenge instance.
     * @param {Partial<FIDO2Challenge>} [$$source = {}] - The source object to create the FIDO2Challenge.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("challenge" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["challenge"] = "";
        }
        if (!("rp_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rp_id"] = "";
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expires_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FIDO2Challenge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FIDO2Challenge}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField3_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("challenge" in $$parsedSource) {
            $$parsedSource["challenge"] = $$createField1_0($$parsedSource["challenge"]);
        }
        if ("user_id" in $$parsedSource) {
            $$parsedSource["user_id"] = $$createField3_0($$parsedSource["user_id"]);
        }
        return new FIDO2Challenge(/** @type {Partial<FIDO2Challenge>} */($$parsedSource));
    }
}

/**
 * FIDO2Credential represents a stored FIDO2/WebAuthn credential
 */
export class FIDO2Credential {
    /**
     * Creates a new FIDO2Credential instance.
     * @param {Partial<FIDO2Credential>} [$$source = {}] - The source object to create the FIDO2Credential.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("public_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_key"] = "";
        }
        if (!("sign_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sign_count"] = 0;
        }
        if (!("device_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_name"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_used_at"] = "";
        }
        if (!("attestation_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["attestation_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FIDO2Credential instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FIDO2Credential}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credential_id" in $$parsedSource) {
            $$parsedSource["credential_id"] = $$createField1_0($$parsedSource["credential_id"]);
        }
        if ("public_key" in $$parsedSource) {
            $$parsedSource["public_key"] = $$createField2_0($$parsedSource["public_key"]);
        }
        return new FIDO2Credential(/** @type {Partial<FIDO2Credential>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const QuorumAction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionKillSwitch: "INGEST_KILL_SWITCH",
    ActionSOARPlaybook: "SOAR_DESTRUCTIVE_EXEC",
    ActionVaultRotation: "VAULT_ROOT_ROTATION",
    ActionCryptoWipe: "GDPR_CRYPTO_WIPE",
};

export class QuorumRequest {
    /**
     * Creates a new QuorumRequest instance.
     * @param {Partial<QuorumRequest>} [$$source = {}] - The source object to create the QuorumRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {QuorumAction}
             */
            this["action"] = QuorumAction.$zero;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("proposer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proposer"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["expires_at"] = null;
        }
        if (!("approvals" in $$source)) {
            /**
             * User IDs who approved
             * @member
             * @type {string[]}
             */
            this["approvals"] = [];
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["required"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ApprovalStatus}
             */
            this["status"] = ApprovalStatus.$zero;
        }
        if (!("payload" in $$source)) {
            /**
             * Action-specific data
             * @member
             * @type {string}
             */
            this["payload"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuorumRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuorumRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("approvals" in $$parsedSource) {
            $$parsedSource["approvals"] = $$createField6_0($$parsedSource["approvals"]);
        }
        return new QuorumRequest(/** @type {Partial<QuorumRequest>} */($$parsedSource));
    }
}

/**
 * YubiKeyInfo holds information about a connected YubiKey
 */
export class YubiKeyInfo {
    /**
     * Creates a new YubiKeyInfo instance.
     * @param {Partial<YubiKeyInfo>} [$$source = {}] - The source object to create the YubiKeyInfo.
     */
    constructor($$source = {}) {
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("piv_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["piv_enabled"] = false;
        }
        if (!("fido_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fido_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YubiKeyInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YubiKeyInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new YubiKeyInfo(/** @type {Partial<YubiKeyInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
