// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RiskScore {
    /**
     * Creates a new RiskScore instance.
     * @param {Partial<RiskScore>} [$$source = {}] - The source object to create the RiskScore.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * "Low", "Medium", "High", "Critical"
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("impact" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["impact"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RiskScore instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RiskScore}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RiskScore(/** @type {Partial<RiskScore>} */($$parsedSource));
    }
}
