// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MetricTrigger defines a threshold-based alert for resource usage
 */
export class MetricTrigger {
    /**
     * Creates a new MetricTrigger instance.
     * @param {Partial<MetricTrigger>} [$$source = {}] - The source object to create the MetricTrigger.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("metric" in $$source)) {
            /**
             * "cpu", "mem_percent", "load", "disk_percent"
             * @member
             * @type {string}
             */
            this["metric"] = "";
        }
        if (!("threshold" in $$source)) {
            /**
             * e.g. 90.0
             * @member
             * @type {number}
             */
            this["threshold"] = 0;
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricTrigger instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricTrigger}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricTrigger(/** @type {Partial<MetricTrigger>} */($$parsedSource));
    }
}

/**
 * Trigger defines a pattern-matching alert rule
 */
export class Trigger {
    /**
     * Creates a new Trigger instance.
     * @param {Partial<Trigger>} [$$source = {}] - The source object to create the Trigger.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * critical, high, medium, low
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Trigger instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Trigger}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Trigger(/** @type {Partial<Trigger>} */($$parsedSource));
    }
}
