// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckDef is an automated check within a control.
 */
export class CheckDef {
    /**
     * Creates a new CheckDef instance.
     * @param {Partial<CheckDef>} [$$source = {}] - The source object to create the CheckDef.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {CheckType}
             */
            this["type"] = CheckType.$zero;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["params"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckDef}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField2_0($$parsedSource["params"]);
        }
        return new CheckDef(/** @type {Partial<CheckDef>} */($$parsedSource));
    }
}

/**
 * CheckType defines the kind of automated compliance check.
 * @readonly
 * @enum {string}
 */
export const CheckType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CheckAuditLogExists: "audit_log_exists",
    CheckMinLogRetentionDays: "min_log_retention_days",
    CheckEncryptionEnabled: "encryption_enabled",
    CheckMFAEnabled: "mfa_enabled",
    CheckTLSEnabled: "tls_enabled",
    CheckFIMEnabled: "fim_enabled",
    CheckRBACEnabled: "rbac_enabled",
    CheckAlertingEnabled: "alerting_enabled",
    CheckFailedLoginThreshold: "failed_login_threshold",
    CheckMerkleIntegrity: "merkle_integrity_valid",
    CheckEvidenceLocker: "evidence_locker_available",
    CheckCompliancePackLoaded: "compliance_pack_loaded",
    CheckAccessReview: "access_review_exists",
    CheckVulnScan: "vulnerability_scan_exists",
};

/**
 * ComplianceReport is a complete audit report
 */
export class ComplianceReport {
    /**
     * Creates a new ComplianceReport instance.
     * @param {Partial<ComplianceReport>} [$$source = {}] - The source object to create the ComplianceReport.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ReportType}
             */
            this["type"] = ReportType.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("generated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generated_at"] = "";
        }
        if (!("period_start" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["period_start"] = "";
        }
        if (!("period_end" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["period_end"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {ReportSummary}
             */
            this["summary"] = (new ReportSummary());
        }
        if (!("sections" in $$source)) {
            /**
             * @member
             * @type {ReportSection[]}
             */
            this["sections"] = [];
        }
        if (!("findings" in $$source)) {
            /**
             * @member
             * @type {Finding[]}
             */
            this["findings"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PackResult[] | undefined}
             */
            this["pack_results"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComplianceReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComplianceReport}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField6_0($$parsedSource["summary"]);
        }
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField7_0($$parsedSource["sections"]);
        }
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField8_0($$parsedSource["findings"]);
        }
        if ("pack_results" in $$parsedSource) {
            $$parsedSource["pack_results"] = $$createField9_0($$parsedSource["pack_results"]);
        }
        return new ComplianceReport(/** @type {Partial<ComplianceReport>} */($$parsedSource));
    }
}

/**
 * ControlDef is a single compliance control within a pack.
 */
export class ControlDef {
    /**
     * Creates a new ControlDef instance.
     * @param {Partial<ControlDef>} [$$source = {}] - The source object to create the ControlDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("checks" in $$source)) {
            /**
             * @member
             * @type {CheckDef[]}
             */
            this["checks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControlDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ControlDef}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField3_0($$parsedSource["checks"]);
        }
        return new ControlDef(/** @type {Partial<ControlDef>} */($$parsedSource));
    }
}

/**
 * ControlResult is the outcome of evaluating a single control.
 */
export class ControlResult {
    /**
     * Creates a new ControlResult instance.
     * @param {Partial<ControlResult>} [$$source = {}] - The source object to create the ControlResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("checks" in $$source)) {
            /**
             * @member
             * @type {EvalResult[]}
             */
            this["checks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControlResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ControlResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField3_0($$parsedSource["checks"]);
        }
        return new ControlResult(/** @type {Partial<ControlResult>} */($$parsedSource));
    }
}

/**
 * EvalResult is the outcome of evaluating a single check.
 */
export class EvalResult {
    /**
     * Creates a new EvalResult instance.
     * @param {Partial<EvalResult>} [$$source = {}] - The source object to create the EvalResult.
     */
    constructor($$source = {}) {
        if (!("check_type" in $$source)) {
            /**
             * @member
             * @type {CheckType}
             */
            this["check_type"] = CheckType.$zero;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EvalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EvalResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EvalResult(/** @type {Partial<EvalResult>} */($$parsedSource));
    }
}

export class Finding {
    /**
     * Creates a new Finding instance.
     * @param {Partial<Finding>} [$$source = {}] - The source object to create the Finding.
     */
    constructor($$source = {}) {
        if (!("severity" in $$source)) {
            /**
             * "critical", "warning", "info"
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remediation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["evidence"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Finding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Finding(/** @type {Partial<Finding>} */($$parsedSource));
    }
}

/**
 * PackDefinition is the YAML schema for a compliance pack.
 */
export class PackDefinition {
    /**
     * Creates a new PackDefinition instance.
     * @param {Partial<PackDefinition>} [$$source = {}] - The source object to create the PackDefinition.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("controls" in $$source)) {
            /**
             * @member
             * @type {ControlDef[]}
             */
            this["controls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("controls" in $$parsedSource) {
            $$parsedSource["controls"] = $$createField5_0($$parsedSource["controls"]);
        }
        return new PackDefinition(/** @type {Partial<PackDefinition>} */($$parsedSource));
    }
}

/**
 * PackResult is the full evaluation of a compliance pack.
 */
export class PackResult {
    /**
     * Creates a new PackResult instance.
     * @param {Partial<PackResult>} [$$source = {}] - The source object to create the PackResult.
     */
    constructor($$source = {}) {
        if (!("pack_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pack_id"] = "";
        }
        if (!("pack_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pack_name"] = "";
        }
        if (!("evaluated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["evaluated_at"] = "";
        }
        if (!("total_controls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_controls"] = 0;
        }
        if (!("passed_controls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passed_controls"] = 0;
        }
        if (!("failed_controls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed_controls"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * 0.0 – 100.0
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("controls" in $$source)) {
            /**
             * @member
             * @type {ControlResult[]}
             */
            this["controls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("controls" in $$parsedSource) {
            $$parsedSource["controls"] = $$createField7_0($$parsedSource["controls"]);
        }
        return new PackResult(/** @type {Partial<PackResult>} */($$parsedSource));
    }
}

export class ReportSection {
    /**
     * Creates a new ReportSection instance.
     * @param {Partial<ReportSection>} [$$source = {}] - The source object to create the ReportSection.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "pass", "fail", "warning", "info"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["details"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportSection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportSection(/** @type {Partial<ReportSection>} */($$parsedSource));
    }
}

export class ReportSummary {
    /**
     * Creates a new ReportSummary instance.
     * @param {Partial<ReportSummary>} [$$source = {}] - The source object to create the ReportSummary.
     */
    constructor($$source = {}) {
        if (!("total_sessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_sessions"] = 0;
        }
        if (!("unique_hosts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unique_hosts"] = 0;
        }
        if (!("total_commands" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_commands"] = 0;
        }
        if (!("avg_session_duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avg_session_duration"] = "";
        }
        if (!("failed_logins" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed_logins"] = 0;
        }
        if (!("compliance_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compliance_score"] = 0;
        }
        if (!("critical_findings" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["critical_findings"] = 0;
        }
        if (!("warning_findings" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["warning_findings"] = 0;
        }
        if (!("info_findings" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["info_findings"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportSummary(/** @type {Partial<ReportSummary>} */($$parsedSource));
    }
}

/**
 * ReportType defines the compliance standard
 * @readonly
 * @enum {string}
 */
export const ReportType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ReportSOC2: "soc2",
    ReportPCIDSS: "pci-dss",
    ReportHIPAA: "hipaa",
    ReportGeneral: "general",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ReportSummary.createFrom;
const $$createType2 = ReportSection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Finding.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PackResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = CheckDef.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = EvalResult.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ControlDef.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ControlResult.createFrom;
const $$createType15 = $Create.Array($$createType14);
