// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Campaign represents a series of simulation scenarios
 */
export class Campaign {
    /**
     * Creates a new Campaign instance.
     * @param {Partial<Campaign>} [$$source = {}] - The source object to create the Campaign.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("scenarios" in $$source)) {
            /**
             * Slice of Scenario IDs
             * @member
             * @type {string[]}
             */
            this["scenarios"] = [];
        }
        if (!("start_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["start_time"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["end_time"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "running", "completed", "failed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("total_steps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_steps"] = 0;
        }
        if (!("passed_steps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passed_steps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Campaign instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Campaign}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scenarios" in $$parsedSource) {
            $$parsedSource["scenarios"] = $$createField2_0($$parsedSource["scenarios"]);
        }
        return new Campaign(/** @type {Partial<Campaign>} */($$parsedSource));
    }
}

/**
 * CoverageReport summarizes detection posture against MITRE ATT&CK.
 */
export class CoverageReport {
    /**
     * Creates a new CoverageReport instance.
     * @param {Partial<CoverageReport>} [$$source = {}] - The source object to create the CoverageReport.
     */
    constructor($$source = {}) {
        if (!("total_techniques" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_techniques"] = 0;
        }
        if (!("covered_techniques" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["covered_techniques"] = 0;
        }
        if (!("gap_techniques" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gap_techniques"] = 0;
        }
        if (!("coverage_percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["coverage_percent"] = 0;
        }
        if (!("tactic_breakdown" in $$source)) {
            /**
             * @member
             * @type {TacticCoverage[]}
             */
            this["tactic_breakdown"] = [];
        }
        if (!("covered_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["covered_ids"] = [];
        }
        if (!("gap_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["gap_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverageReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoverageReport}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tactic_breakdown" in $$parsedSource) {
            $$parsedSource["tactic_breakdown"] = $$createField4_0($$parsedSource["tactic_breakdown"]);
        }
        if ("covered_ids" in $$parsedSource) {
            $$parsedSource["covered_ids"] = $$createField5_0($$parsedSource["covered_ids"]);
        }
        if ("gap_ids" in $$parsedSource) {
            $$parsedSource["gap_ids"] = $$createField6_0($$parsedSource["gap_ids"]);
        }
        return new CoverageReport(/** @type {Partial<CoverageReport>} */($$parsedSource));
    }
}

/**
 * PurpleTeamReport is the composite scoring model for the Purple Team dashboard.
 */
export class PurpleTeamReport {
    /**
     * Creates a new PurpleTeamReport instance.
     * @param {Partial<PurpleTeamReport>} [$$source = {}] - The source object to create the PurpleTeamReport.
     */
    constructor($$source = {}) {
        if (!("resilience_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resilience_score"] = 0;
        }
        if (!("resilience_grade" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resilience_grade"] = "";
        }
        if (!("detection_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detection_rate"] = 0;
        }
        if (!("coverage_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["coverage_index"] = 0;
        }
        if (!("mean_response_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mean_response_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ValidationRun | null | undefined}
             */
            this["last_validation"] = undefined;
        }
        if (!("validation_history" in $$source)) {
            /**
             * @member
             * @type {ValidationRun[]}
             */
            this["validation_history"] = [];
        }
        if (!("coverage" in $$source)) {
            /**
             * @member
             * @type {CoverageReport}
             */
            this["coverage"] = (new CoverageReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PurpleTeamReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PurpleTeamReport}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_validation" in $$parsedSource) {
            $$parsedSource["last_validation"] = $$createField5_0($$parsedSource["last_validation"]);
        }
        if ("validation_history" in $$parsedSource) {
            $$parsedSource["validation_history"] = $$createField6_0($$parsedSource["validation_history"]);
        }
        if ("coverage" in $$parsedSource) {
            $$parsedSource["coverage"] = $$createField7_0($$parsedSource["coverage"]);
        }
        return new PurpleTeamReport(/** @type {Partial<PurpleTeamReport>} */($$parsedSource));
    }
}

/**
 * Scenario represents a predefined attack pattern
 */
export class Scenario {
    /**
     * Creates a new Scenario instance.
     * @param {Partial<Scenario>} [$$source = {}] - The source object to create the Scenario.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("target_type" in $$source)) {
            /**
             * e.g., "host", "user", "file"
             * @member
             * @type {string}
             */
            this["target_type"] = "";
        }
        if (!("mitre_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mitre_id"] = "";
        }
        if (!("tactics" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tactics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scenario instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Scenario}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tactics" in $$parsedSource) {
            $$parsedSource["tactics"] = $$createField5_0($$parsedSource["tactics"]);
        }
        return new Scenario(/** @type {Partial<Scenario>} */($$parsedSource));
    }
}

/**
 * SimulationResult tracks the outcome of a simulation
 */
export class SimulationResult {
    /**
     * Creates a new SimulationResult instance.
     * @param {Partial<SimulationResult>} [$$source = {}] - The source object to create the SimulationResult.
     */
    constructor($$source = {}) {
        if (!("scenario_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scenario_id"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["alert_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimulationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SimulationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SimulationResult(/** @type {Partial<SimulationResult>} */($$parsedSource));
    }
}

/**
 * TacticCoverage represents per-tactic detection coverage.
 */
export class TacticCoverage {
    /**
     * Creates a new TacticCoverage instance.
     * @param {Partial<TacticCoverage>} [$$source = {}] - The source object to create the TacticCoverage.
     */
    constructor($$source = {}) {
        if (!("tactic_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tactic_id"] = "";
        }
        if (!("tactic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tactic"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("covered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["covered"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("techniques" in $$source)) {
            /**
             * @member
             * @type {TechniqueStatus[]}
             */
            this["techniques"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TacticCoverage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TacticCoverage}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("techniques" in $$parsedSource) {
            $$parsedSource["techniques"] = $$createField5_0($$parsedSource["techniques"]);
        }
        return new TacticCoverage(/** @type {Partial<TacticCoverage>} */($$parsedSource));
    }
}

/**
 * TechniqueStatus indicates whether a specific technique has active detection.
 */
export class TechniqueStatus {
    /**
     * Creates a new TechniqueStatus instance.
     * @param {Partial<TechniqueStatus>} [$$source = {}] - The source object to create the TechniqueStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("covered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["covered"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * linked scenario ID
             * @member
             * @type {string | undefined}
             */
            this["scenario"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TechniqueStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TechniqueStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TechniqueStatus(/** @type {Partial<TechniqueStatus>} */($$parsedSource));
    }
}

/**
 * ValidationRun captures the outcome of a continuous validation pass.
 */
export class ValidationRun {
    /**
     * Creates a new ValidationRun instance.
     * @param {Partial<ValidationRun>} [$$source = {}] - The source object to create the ValidationRun.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("total_scenarios" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_scenarios"] = 0;
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detected"] = 0;
        }
        if (!("missed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missed"] = 0;
        }
        if (!("pass_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pass_rate"] = 0;
        }
        if (!("coverage_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["coverage_index"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationRun instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationRun}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationRun(/** @type {Partial<ValidationRun>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TacticCoverage.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ValidationRun.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType3);
const $$createType6 = CoverageReport.createFrom;
const $$createType7 = TechniqueStatus.createFrom;
const $$createType8 = $Create.Array($$createType7);
