// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SimulationService manages threat simulations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<($models.Campaign | null)[]>}
 */
export function GetCampaigns() {
    return $Call.ByID(2194691592).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCoverageReport computes detection coverage across the MITRE ATT&CK matrix.
 * @returns {$CancellablePromise<$models.CoverageReport>}
 */
export function GetCoverageReport() {
    return $Call.ByID(3891027309).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPurpleTeamReport builds the composite Purple Team scoring report.
 * @returns {$CancellablePromise<$models.PurpleTeamReport>}
 */
export function GetPurpleTeamReport() {
    return $Call.ByID(2864046020).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.SimulationResult | null)[]>}
 */
export function GetResults() {
    return $Call.ByID(2298953469).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetValidationHistory returns past validation runs.
 * @returns {$CancellablePromise<$models.ValidationRun[]>}
 */
export function GetValidationHistory() {
    return $Call.ByID(1588329234).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListScenarios returns available attack patterns
 * @returns {$CancellablePromise<$models.Scenario[]>}
 */
export function ListScenarios() {
    return $Call.ByID(1518490886).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2413398664);
}

/**
 * RunContinuousValidation executes all scenarios and records the outcome.
 * @returns {$CancellablePromise<void>}
 */
export function RunContinuousValidation() {
    return $Call.ByID(3259717200);
}

/**
 * RunScenario triggers a simulation
 * @param {string} id
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function RunScenario(id, target) {
    return $Call.ByID(1009500886, id, target);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1982484153);
}

/**
 * @param {string} name
 * @param {string[]} scenarios
 * @returns {$CancellablePromise<string>}
 */
export function StartCampaign(name, scenarios) {
    return $Call.ByID(802613319, name, scenarios);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(2629470388);
}

// Private type creation functions
const $$createType0 = $models.Campaign.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CoverageReport.createFrom;
const $$createType4 = $models.PurpleTeamReport.createFrom;
const $$createType5 = $models.SimulationResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ValidationRun.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.Scenario.createFrom;
const $$createType11 = $Create.Array($$createType10);
