// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(428909566).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExplainError asks the AI to explain a terminal error
 * @param {string} errorOutput
 * @returns {$CancellablePromise<$models.AIResponse | null>}
 */
export function ExplainError(errorOutput) {
    return $Call.ByID(1115289596, errorOutput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GenerateCommand asks the AI to generate a shell command from natural language
 * @param {string} description
 * @returns {$CancellablePromise<$models.AIResponse | null>}
 */
export function GenerateCommand(description) {
    return $Call.ByID(543360437, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Message[]>}
 */
export function GetChatHistory() {
    return $Call.ByID(229217293).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1298215928);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(content) {
    return $Call.ByID(3503322788, content);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(738957761);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1818217787);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.AIResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.Message.createFrom;
const $$createType4 = $Create.Array($$createType3);
