// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertingService exposes alert and notification configuration to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analytics$0 from "../analytics/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detection$0 from "../detection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../notifications/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as osquery$0 from "../osquery/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @param {string} name
 * @param {string} pattern
 * @param {string} severity
 * @returns {$CancellablePromise<void>}
 */
export function AddTrigger(id, name, pattern, severity) {
    return $Call.ByID(2986610590, id, name, pattern, severity);
}

/**
 * CheckGlobalSecurityThresholds evaluates fleet-wide security posture
 * @returns {$CancellablePromise<void>}
 */
export function CheckGlobalSecurityThresholds() {
    return $Call.ByID(2946991760);
}

/**
 * Dependencies returns service dependencies.
 * siem-service must be started before alerting can process SIEM events.
 * eventbus is infrastructure wired at construction time, not a kernel-managed service.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2877100702).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetAlertHistory() {
    return $Call.ByID(3117472659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetDetectionRules exposes active YAML rules (including MITRE info) to the UI
 * @returns {$CancellablePromise<detection$0.Rule[]>}
 */
export function GetDetectionRules() {
    return $Call.ByID(386465259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetEvaluator returns the underlying detection evaluator.
 * Used by integration tests to directly exercise sigma loading.
 * @returns {$CancellablePromise<detection$0.Evaluator | null>}
 */
export function GetEvaluator() {
    return $Call.ByID(1690458786).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<analytics$0.MetricTrigger[]>}
 */
export function GetMetricTriggers() {
    return $Call.ByID(3433667748).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<notifications$0.NotificationConfig>}
 */
export function GetNotificationConfig() {
    return $Call.ByID(548075288).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<osquery$0.QueryTemplate[]>}
 */
export function GetOsqueryTemplates() {
    return $Call.ByID(2895930792).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetRuleVerifications exposes the AST static analysis results to the Policy Verifier UI
 * @returns {$CancellablePromise<detection$0.ValidationResult[]>}
 */
export function GetRuleVerifications() {
    return $Call.ByID(2185691973).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<analytics$0.Trigger[]>}
 */
export function GetTriggers() {
    return $Call.ByID(3204068728).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ListIncidents retrieves security incidents filtered by status
 * @param {string} status
 * @param {number} limit
 * @returns {$CancellablePromise<database$0.Incident[]>}
 */
export function ListIncidents(status, limit) {
    return $Call.ByID(1152987342, status, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2399676824);
}

/**
 * ReloadSigmaRules is the Wails-facing manual reload trigger.
 * @returns {$CancellablePromise<number>}
 */
export function ReloadSigmaRules() {
    return $Call.ByID(3013217548);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMetricTrigger(id) {
    return $Call.ByID(2662491437, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTrigger(id) {
    return $Call.ByID(265263009, id);
}

/**
 * @param {$models.SuppressionService | null} svc
 * @returns {$CancellablePromise<void>}
 */
export function SetSuppressionService(svc) {
    return $Call.ByID(482794031, svc);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3538781153);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3302559451);
}

/**
 * TestNotification sends a test alert through all enabled channels
 * @returns {$CancellablePromise<void>}
 */
export function TestNotification() {
    return $Call.ByID(3068591352);
}

/**
 * UpdateIncidentStatus transitions an incident to a new status
 * @param {string} id
 * @param {string} status
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function UpdateIncidentStatus(id, status, reason) {
    return $Call.ByID(495293342, id, status, reason);
}

/**
 * @param {analytics$0.MetricTrigger} mt
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMetricTrigger(mt) {
    return $Call.ByID(625272094, mt);
}

/**
 * @param {notifications$0.NotificationConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNotificationConfig(cfg) {
    return $Call.ByID(529089331, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = detection$0.Rule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = detection$0.Evaluator.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = analytics$0.MetricTrigger.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = notifications$0.NotificationConfig.createFrom;
const $$createType10 = osquery$0.QueryTemplate.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = detection$0.ValidationResult.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = analytics$0.Trigger.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = database$0.Incident.createFrom;
const $$createType17 = $Create.Array($$createType16);
