// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AnalyticsService provides log searching and dashboard configuration via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oql$0 from "../oql/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(381570580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetEntityEnrichment provides real-time context (GeoIP, Threat Intel) for a specific entity.
 * @param {string} entityID
 * @param {string} entityType
 * @returns {$CancellablePromise<$models.EntityEnrichment | null>}
 */
export function GetEntityEnrichment(entityID, entityType) {
    return $Call.ByID(2715078377, entityID, entityType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetRecordingFrames retrieves the full TTY frame sequence for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetRecordingFrames(sessionID) {
    return $Call.ByID(1152275580, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * LoadDashboard retrieves a saved dashboard layout.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function LoadDashboard(id) {
    return $Call.ByID(1080556699, id);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(3060109666);
}

/**
 * RunOQL executes an OQL query. It prefers BadgerDB for system-wide SIEM logs
 * but falls back to SQLite for terminal-specific telemetry if needed.
 * @param {string} query
 * @returns {$CancellablePromise<oql$0.QueryResult | null>}
 */
export function RunOQL(query) {
    return $Call.ByID(4058330550, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RunOsquery executes an osquery-style query (stub — osquery integration planned for Phase 6).
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function RunOsquery(query) {
    return $Call.ByID(1588814972, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RunWidgetQuery executes a dashboard widget query.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function RunWidgetQuery(query, limit) {
    return $Call.ByID(1715129238, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SaveDashboard stores a dashboard layout as JSON.
 * @param {string} id
 * @param {string} layoutJSON
 * @returns {$CancellablePromise<void>}
 */
export function SaveDashboard(id, layoutJSON) {
    return $Call.ByID(533596704, id, layoutJSON);
}

/**
 * SearchLogs executes queries against the local Analytics Engine.
 * @param {string} query
 * @param {string} mode
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function SearchLogs(query, mode, limit, offset) {
    return $Call.ByID(3113331478, query, mode, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(407051659);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(906828409);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.EntityEnrichment.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = oql$0.QueryResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
