// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookmarkService is a Wails-bound service for SSH host bookmark management.
 * Wraps HostStore with Vault-encrypted credential handling.
 * This gives the frontend a Termius-like host management experience.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create adds a new SSH host bookmark. Password is encrypted via Vault.
 * @param {$models.BookmarkCreateInput} input
 * @returns {$CancellablePromise<$models.BookmarkEntry | null>}
 */
export function Create(input) {
    return $Call.ByID(1607031657, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Delete removes a bookmark permanently.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2303469726, id);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(174895140).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAllTags returns all unique tags used across bookmarks.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllTags() {
    return $Call.ByID(1971397687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetByTag returns bookmarks with a specific tag.
 * @param {string} tag
 * @returns {$CancellablePromise<$models.BookmarkEntry[]>}
 */
export function GetByTag(tag) {
    return $Call.ByID(2579863990, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCount returns the total number of bookmarks.
 * @returns {$CancellablePromise<number>}
 */
export function GetCount() {
    return $Call.ByID(1823384458);
}

/**
 * GetFavorites returns only bookmarks marked as favorites.
 * @returns {$CancellablePromise<$models.BookmarkEntry[]>}
 */
export function GetFavorites() {
    return $Call.ByID(1937982288).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListAll returns all SSH host bookmarks.
 * @returns {$CancellablePromise<$models.BookmarkEntry[]>}
 */
export function ListAll() {
    return $Call.ByID(982027780).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1160791154);
}

/**
 * QuickSearch performs a fuzzy search across labels, hostnames, and tags.
 * @param {string} query
 * @returns {$CancellablePromise<$models.BookmarkEntry[]>}
 */
export function QuickSearch(query) {
    return $Call.ByID(996471276, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Search finds bookmarks matching a query (hostname, label, tags).
 * @param {string} query
 * @returns {$CancellablePromise<$models.BookmarkEntry[]>}
 */
export function Search(query) {
    return $Call.ByID(1791678949, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(4195236091);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3348133545);
}

/**
 * ToggleFavorite toggles the favorite status of a bookmark.
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleFavorite(id) {
    return $Call.ByID(3059910761, id);
}

/**
 * Update modifies an existing bookmark.
 * @param {string} id
 * @param {$models.BookmarkCreateInput} input
 * @returns {$CancellablePromise<$models.BookmarkEntry | null>}
 */
export function Update(id, input) {
    return $Call.ByID(4277829624, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BookmarkEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
