// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ComplianceService exposes compliance reporting and data integrity to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as compliance$0 from "../compliance/models.js";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2471069671).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * EvaluatePack runs a compliance evaluation for a specific pack.
 * @param {string} packID
 * @returns {$CancellablePromise<compliance$0.PackResult | null>}
 */
export function EvaluatePack(packID) {
    return $Call.ByID(2349426180, packID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExportReportPDF generates a PDF for a report and returns the file path.
 * @param {string} reportType
 * @param {number} startUnix
 * @param {number} endUnix
 * @returns {$CancellablePromise<string>}
 */
export function ExportReportPDF(reportType, startUnix, endUnix) {
    return $Call.ByID(3075423680, reportType, startUnix, endUnix);
}

/**
 * GenerateReport creates a new compliance report
 * @param {string} reportType
 * @param {number} startUnix
 * @param {number} endUnix
 * @returns {$CancellablePromise<compliance$0.ComplianceReport | null>}
 */
export function GenerateReport(reportType, startUnix, endUnix) {
    return $Call.ByID(1469068531, reportType, startUnix, endUnix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListCompliancePacks returns all loaded compliance packs.
 * @returns {$CancellablePromise<compliance$0.PackDefinition[]>}
 */
export function ListCompliancePacks() {
    return $Call.ByID(2048570901).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListReports returns previously generated reports
 * @returns {$CancellablePromise<compliance$0.ComplianceReport[]>}
 */
export function ListReports() {
    return $Call.ByID(464427221).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Name returns the name of the service
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(4197341393);
}

/**
 * SignData generates a secure HMAC-SHA256 signature for the given payload using the vault's master key
 * @param {string} payload
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function SignData(payload) {
    return $Call.ByID(2392873631, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Startup initializes the service
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(100482226);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3167843058);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = compliance$0.PackResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = compliance$0.ComplianceReport.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = compliance$0.PackDefinition.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType3);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
