// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CounterfactualService exposes counterfactual simulation to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detection$0 from "../detection/models.js";

/**
 * AnalyzeRuleImpact runs a focused simulation for a single rule.
 * @param {string} ruleID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function AnalyzeRuleImpact(ruleID) {
    return $Call.ByID(3880347523, ruleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3286253020).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListRules returns the current rule IDs available for simulation.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListRules() {
    return $Call.ByID(3479407656).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2227963226);
}

/**
 * RunCounterfactual runs a counterfactual simulation with the specified rules disabled.
 * @param {string[]} disabledRuleIDs
 * @returns {$CancellablePromise<detection$0.CounterfactualResult | null>}
 */
export function RunCounterfactual(disabledRuleIDs) {
    return $Call.ByID(2235499774, disabledRuleIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(894561811);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(410042081);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = detection$0.CounterfactualResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
