// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DisasterService handles disaster recovery, kill-switch safe-mode,
 * encrypted snapshots, and air-gap operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ActivateAirGapMode disables all outbound network.
 * @returns {$CancellablePromise<void>}
 */
export function ActivateAirGapMode() {
    return $Call.ByID(3235738352);
}

/**
 * ActivateKillSwitch enters read-only safe mode.
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function ActivateKillSwitch(reason) {
    return $Call.ByID(3479234835, reason);
}

/**
 * DeactivateKillSwitch returns to normal mode.
 * @returns {$CancellablePromise<void>}
 */
export function DeactivateKillSwitch() {
    return $Call.ByID(1686149148);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(687846207).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateResilienceBundle exports a signed, encrypted dead-drop archive.
 * @param {string} passphrase
 * @returns {$CancellablePromise<string>}
 */
export function ExportResilienceBundle(passphrase) {
    return $Call.ByID(1300991637, passphrase);
}

/**
 * GetMode returns the current operational mode.
 * @returns {$CancellablePromise<string>}
 */
export function GetMode() {
    return $Call.ByID(3484896133);
}

/**
 * ImportResilienceBundle restores data from a dead-drop archive.
 * @param {string} path
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function ImportResilienceBundle(path, passphrase) {
    return $Call.ByID(794030694, path, passphrase);
}

/**
 * Name returns the service name.
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2368330169);
}

/**
 * Startup initialises the service.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3537761386);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2247401226);
}

/**
 * TriggerNuclearDestruction performs the ultimate data sanitization.
 * @returns {$CancellablePromise<void>}
 */
export function TriggerNuclearDestruction() {
    return $Call.ByID(1876620056);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
