// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService exposes host discovery functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../discovery/models.js";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(519790586).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DiscoverAll runs all sources to find local networks hosts and configuration hosts
 * @returns {$CancellablePromise<discovery$0.DiscoveredHost[]>}
 */
export function DiscoverAll() {
    return $Call.ByID(3722199623).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * NewDiscoveryService creates a new DiscoveryService
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1698890348);
}

/**
 * Startup is called at application startup
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1092985477);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(421752791);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = discovery$0.DiscoveredHost.createFrom;
const $$createType2 = $Create.Array($$createType1);
