// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService implements the FileManager interface by dispatching to local or remote providers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2219149626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @param {string} destPath
 * @param {number} size
 * @returns {$CancellablePromise<string>}
 */
export function Download(ctxID, path, destPath, size) {
    return $Call.ByID(2913614971, ctxID, path, destPath, size);
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(ctxID, path) {
    return $Call.ByID(1091336590, ctxID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(ctxID, path) {
    return $Call.ByID(1193255414, ctxID, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(749951660);
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(ctxID, path) {
    return $Call.ByID(1437693965, ctxID, path);
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Remove(ctxID, path) {
    return $Call.ByID(3523258483, ctxID, path);
}

/**
 * @param {string} ctxID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function Rename(ctxID, oldPath, newPath) {
    return $Call.ByID(436628997, ctxID, oldPath, newPath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(315127493);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3726307863);
}

/**
 * @param {string} ctxID
 * @param {string} localPath
 * @param {string} destPath
 * @returns {$CancellablePromise<string>}
 */
export function Upload(ctxID, localPath, destPath) {
    return $Call.ByID(317850482, ctxID, localPath, destPath);
}

/**
 * @param {string} ctxID
 * @param {string} path
 * @param {string} contentBase64
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(ctxID, path, contentBase64) {
    return $Call.ByID(679045812, ctxID, path, contentBase64);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.FileInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
