// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ForensicsService exposes forensic evidence management to the frontend via Wails.
 * This is DESKTOP-ONLY — it uses local hardware (disks, memory, TPM) and must
 * never be exposed to the Web layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forensics$0 from "../forensics/models.js";

/**
 * AcquireDiskImage performs a raw disk acquisition and stores it in the evidence locker.
 * [CAUTION] Requires admin privileges. Desktop-only operation.
 * @param {string} devicePath
 * @param {string} incidentID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function AcquireDiskImage(devicePath, incidentID) {
    return $Call.ByID(2951032545, devicePath, incidentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AcquireMemoryDump captures the physical memory of the local machine.
 * [CAUTION] Requires admin privileges. Desktop-only operation.
 * @param {string} incidentID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function AcquireMemoryDump(incidentID) {
    return $Call.ByID(60318780, incidentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AnalyzeEvidence records an analysis action.
 * @param {string} itemID
 * @param {string} analyst
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function AnalyzeEvidence(itemID, analyst, notes) {
    return $Call.ByID(3477755716, itemID, analyst, notes);
}

/**
 * AnalyzeFile conducts a deep forensic entropy analysis.
 * @param {string} itemID
 * @returns {$CancellablePromise<forensics$0.ForensicReport | null>}
 */
export function AnalyzeFile(itemID) {
    return $Call.ByID(654983011, itemID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CollectEvidence creates a new evidence item for an incident.
 * @param {string} incidentID
 * @param {string} evidenceType
 * @param {string} name
 * @param {string} dataBase64
 * @param {string} collector
 * @param {string} notes
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CollectEvidence(incidentID, evidenceType, name, dataBase64, collector, notes) {
    return $Call.ByID(1706001442, incidentID, evidenceType, name, dataBase64, collector, notes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1142527814).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetChainOfCustody returns just the chain for a specific evidence item.
 * @param {string} itemID
 * @returns {$CancellablePromise<forensics$0.ChainEntry[]>}
 */
export function GetChainOfCustody(itemID) {
    return $Call.ByID(789667170, itemID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetEvidence returns a single evidence item with full chain of custody.
 * @param {string} itemID
 * @returns {$CancellablePromise<forensics$0.EvidenceItem | null>}
 */
export function GetEvidence(itemID) {
    return $Call.ByID(785773892, itemID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsHardwareRooted returns true if chain-of-custody signatures are hardware-anchored.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsHardwareRooted() {
    return $Call.ByID(1254411090);
}

/**
 * ListEvidence returns all evidence for an incident.
 * @param {string} incidentID
 * @returns {$CancellablePromise<(forensics$0.EvidenceItem | null)[]>}
 */
export function ListEvidence(incidentID) {
    return $Call.ByID(3624376766, incidentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Name returns the service name.
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2867803568);
}

/**
 * SealEvidence marks evidence as sealed — no further modifications.
 * @param {string} itemID
 * @param {string} sealer
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function SealEvidence(itemID, sealer, notes) {
    return $Call.ByID(75999819, itemID, sealer, notes);
}

/**
 * Startup initializes the service.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3444599273);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1490871811);
}

/**
 * TransferEvidence records a custody transfer.
 * @param {string} itemID
 * @param {string} toActor
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function TransferEvidence(itemID, toActor, notes) {
    return $Call.ByID(1544242597, itemID, toActor, notes);
}

/**
 * VerifyEvidence checks the chain-of-custody integrity.
 * @param {string} itemID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function VerifyEvidence(itemID) {
    return $Call.ByID(1799368743, itemID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = forensics$0.ForensicReport.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = forensics$0.ChainEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = forensics$0.EvidenceItem.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
