// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FusionService bridges the AttackFusionEngine with the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detection$0 from "../detection/models.js";

/**
 * Dependencies returns naming dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(4123945448).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetActiveCampaigns returns all currently tracked attack campaigns.
 * @returns {$CancellablePromise<detection$0.Campaign[]>}
 */
export function GetActiveCampaigns() {
    return $Call.ByID(3705714444).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCampaign returns details for a specific entity.
 * @param {string} entityID
 * @returns {$CancellablePromise<detection$0.Campaign | null>}
 */
export function GetCampaign(entityID) {
    return $Call.ByID(2254727617, entityID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCampaignTimeline reconstructs the causality-linked story of an attack.
 * @param {string} entityID
 * @returns {$CancellablePromise<detection$0.CampaignTimeline | null>}
 */
export function GetCampaignTimeline(entityID) {
    return $Call.ByID(1333408386, entityID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Name returns the service identifier.
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1063012190);
}

/**
 * Start matches the platform.Service interface.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(260146439);
}

/**
 * Stop matches the platform.Service interface.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1744209325);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = detection$0.Campaign.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
const $$createType4 = detection$0.CampaignTimeline.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
