// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GraphService exposes the Security Graph Engine to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} $from
 * @param {string} to
 * @param {string} edgeType
 * @returns {$CancellablePromise<void>}
 */
export function AddEdge($from, to, edgeType) {
    return $Call.ByID(2801656213, $from, to, edgeType);
}

/**
 * AddNode allows the frontend or other services to manually inject graph data.
 * @param {string} id
 * @param {string} nodeType
 * @param {{ [_ in string]?: string }} meta
 * @returns {$CancellablePromise<void>}
 */
export function AddNode(id, nodeType, meta) {
    return $Call.ByID(775228108, id, nodeType, meta);
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2411023812).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FindAttackPath calculates the shortest path between two nodes.
 * @param {string} startID
 * @param {string} endID
 * @returns {$CancellablePromise<string[]>}
 */
export function FindAttackPath(startID, endID) {
    return $Call.ByID(3630232497, startID, endID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSubGraph returns a subset of the graph centered on a target entity.
 * @param {string} nodeID
 * @param {number} hops
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSubGraph(nodeID, hops) {
    return $Call.ByID(270312541, nodeID, hops).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1076726290);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1950877211);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3263965513);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
