// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthService exposes health checking functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1969095118).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAllHealth returns the health of all monitored hosts and internally registered services
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetAllHealth() {
    return $Call.ByID(3298952634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetHealth returns the health of a specific host
 * @param {string} hostID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetHealth(hostID) {
    return $Call.ByID(4284253831, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Name returns the name of the service
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(325222344);
}

/**
 * RegisterHost adds a host to be monitored
 * @param {string} hostID
 * @param {string} address
 * @returns {$CancellablePromise<void>}
 */
export function RegisterHost(hostID, address) {
    return $Call.ByID(2569064960, hostID, address);
}

/**
 * Startup is called at application startup
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3187187953);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(235661099);
}

/**
 * UnregisterHost removes a host from monitoring
 * @param {string} hostID
 * @returns {$CancellablePromise<void>}
 */
export function UnregisterHost(hostID) {
    return $Call.ByID(888183031, hostID);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
