// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IdentityService exposes identity, authentication and RBAC operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckPermission verifies if a user has the required permission
 * @param {string} userID
 * @param {string} permission
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckPermission(userID, permission) {
    return $Call.ByID(2375332098, userID, permission);
}

/**
 * @param {database$0.IdentityConnector | null} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateConnector(c) {
    return $Call.ByID(3209208862, c);
}

/**
 * CreateRole creates a new custom role
 * @param {string} name
 * @param {string} description
 * @param {string[]} permissions
 * @returns {$CancellablePromise<database$0.Role | null>}
 */
export function CreateRole(name, description, permissions) {
    return $Call.ByID(1057707959, name, description, permissions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateUser creates a new local user with a hashed password
 * @param {string} email
 * @param {string} name
 * @param {string} password
 * @param {string} roleID
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function CreateUser(email, name, password, roleID) {
    return $Call.ByID(163746992, email, name, password, roleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnector(id) {
    return $Call.ByID(3881588939, id);
}

/**
 * DeleteUser removes a user
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteUser(id) {
    return $Call.ByID(2581269667, id);
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2628621486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<database$0.IdentityConnector | null>}
 */
export function GetConnector(id) {
    return $Call.ByID(1357808456, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetOIDCURL returns the redirect URL for the configured OIDC provider
 * @returns {$CancellablePromise<string>}
 */
export function GetOIDCURL() {
    return $Call.ByID(2882877785);
}

/**
 * GetSAMLURL returns the redirect URL for the configured SAML IdP
 * @returns {$CancellablePromise<string>}
 */
export function GetSAMLURL() {
    return $Call.ByID(3105545833);
}

/**
 * GetSecurityStats returns a snapshot of global identity hardening
 * @returns {$CancellablePromise<$models.SecurityStats>}
 */
export function GetSecurityStats() {
    return $Call.ByID(2627945726).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetUser returns a single user by ID
 * @param {string} id
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function GetUser(id) {
    return $Call.ByID(2970862970, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetUserByEmail returns a single user by email
 * @param {string} email
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function GetUserByEmail(email) {
    return $Call.ByID(3872353825, email).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetUserByExternalID finds a user by their IdP external identifier
 * @param {string} extID
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function GetUserByExternalID(extID) {
    return $Call.ByID(571451101, extID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * HandleOIDCCallback processes the OIDC authorization code
 * @param {string} code
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function HandleOIDCCallback(code) {
    return $Call.ByID(4271440379, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * HandleSAMLCallback processes the SAML assertion
 * @param {string} data
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function HandleSAMLCallback(data) {
    return $Call.ByID(2594692747, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<database$0.IdentityConnector[]>}
 */
export function ListConnectors() {
    return $Call.ByID(1864735023).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListRoles returns all roles in the current tenant
 * @returns {$CancellablePromise<database$0.Role[]>}
 */
export function ListRoles() {
    return $Call.ByID(2314395700).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListUsers returns all users in the current tenant
 * @returns {$CancellablePromise<database$0.User[]>}
 */
export function ListUsers() {
    return $Call.ByID(2793001185).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * LoginHardwareBound handles authentication using a hardware-rooted signature
 * @param {string} email
 * @param {string} nonce
 * @param {string} signature
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function LoginHardwareBound(email, nonce, signature) {
    return $Call.ByID(1083809856, email, nonce, signature).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * LoginLocal authenticates a user with email and password
 * @param {string} email
 * @param {string} password
 * @returns {$CancellablePromise<database$0.User | null>}
 */
export function LoginLocal(email, password) {
    return $Call.ByID(3633595211, email, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(758324392);
}

/**
 * ProvisionSCIMUser handles automated provisioning from an IdP
 * @param {database$0.User | null} u
 * @returns {$CancellablePromise<void>}
 */
export function ProvisionSCIMUser(u) {
    return $Call.ByID(3100601533, u);
}

/**
 * SetupTOTP generates a new TOTP secret and QR code for the user
 * @param {string} userID
 * @returns {$CancellablePromise<auth$0.TOTPSetupResult | null>}
 */
export function SetupTOTP(userID) {
    return $Call.ByID(2045895057, userID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2912778321);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(244305675);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TriggerSync(id) {
    return $Call.ByID(2181768738, id);
}

/**
 * @param {database$0.IdentityConnector | null} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnector(c) {
    return $Call.ByID(1634204541, c);
}

/**
 * UpdateRole modifies an existing role's permissions
 * @param {string} roleID
 * @param {string} name
 * @param {string} description
 * @param {string[]} permissions
 * @returns {$CancellablePromise<void>}
 */
export function UpdateRole(roleID, name, description, permissions) {
    return $Call.ByID(3754735778, roleID, name, description, permissions);
}

/**
 * UpdateUserRole assigns a new role to a user
 * @param {string} userID
 * @param {string} roleID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateUserRole(userID, roleID) {
    return $Call.ByID(2564683065, userID, roleID);
}

/**
 * ValidateMFA checks a TOTP code for login verification
 * @param {string} userID
 * @param {string} code
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateMFA(userID, code) {
    return $Call.ByID(12186201, userID, code);
}

/**
 * VerifyAndEnableMFA takes a 6-digit code, validates it, and enables MFA
 * @param {string} userID
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function VerifyAndEnableMFA(userID, code) {
    return $Call.ByID(1314042246, userID, code);
}

// Private type creation functions
const $$createType0 = database$0.Role.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = database$0.User.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = database$0.IdentityConnector.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.SecurityStats.createFrom;
const $$createType8 = $Create.Array($$createType5);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType2);
const $$createType11 = auth$0.TOTPSetupResult.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
