// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IncidentService handles the lifecycle of security incidents and forensic cases.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

/**
 * AssignIncident assigns a case to a specific analyst/owner.
 * @param {string} id
 * @param {string} owner
 * @returns {$CancellablePromise<void>}
 */
export function AssignIncident(id, owner) {
    return $Call.ByID(111182016, id, owner);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(936237978).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetByRuleAndGroup proxy for detection engine.
 * @param {string} ruleID
 * @param {string} groupKey
 * @returns {$CancellablePromise<database$0.Incident | null>}
 */
export function GetByRuleAndGroup(ruleID, groupKey) {
    return $Call.ByID(3932087254, ruleID, groupKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetEvidence retrieves all forensic artifacts linked to an incident.
 * @param {string} incidentID
 * @returns {$CancellablePromise<database$0.EvidenceItem[]>}
 */
export function GetEvidence(incidentID) {
    return $Call.ByID(3203227464, incidentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetIncident retrieves a specific case by ID.
 * @param {string} id
 * @returns {$CancellablePromise<database$0.Incident | null>}
 */
export function GetIncident(id) {
    return $Call.ByID(2646313587, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTimeline reconstructs the event sequence for an incident.
 * @param {string} incidentID
 * @returns {$CancellablePromise<database$0.AuditLog[]>}
 */
export function GetTimeline(incidentID) {
    return $Call.ByID(1473063834, incidentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListIncidents retrieves incidents with optional filtering.
 * @param {string} status
 * @param {string} owner
 * @param {number} limit
 * @returns {$CancellablePromise<database$0.Incident[]>}
 */
export function ListIncidents(status, owner, limit) {
    return $Call.ByID(2023648698, status, owner, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(799393036);
}

/**
 * Search proxy for backward compatibility with AlertingService.
 * @param {string} status
 * @param {string} owner
 * @param {number} limit
 * @returns {$CancellablePromise<database$0.Incident[]>}
 */
export function Search(status, owner, limit) {
    return $Call.ByID(3484143775, status, owner, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1407969189);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3775646071);
}

/**
 * UpdateIncidentStatus changes the workflow state of a case.
 * @param {string} id
 * @param {string} status
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function UpdateIncidentStatus(id, status, reason) {
    return $Call.ByID(2626792026, id, status, reason);
}

/**
 * UpdateStatus proxy for backward compatibility with AlertingService.
 * @param {string} id
 * @param {string} status
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function UpdateStatus(id, status, reason) {
    return $Call.ByID(3109352352, id, status, reason);
}

/**
 * Upsert proxy for incident storage with automated triage (Phase 20.9).
 * @param {database$0.Incident | null} incident
 * @returns {$CancellablePromise<void>}
 */
export function Upsert(incident) {
    return $Call.ByID(3833793076, incident);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = database$0.Incident.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = database$0.EvidenceItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = database$0.AuditLog.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType1);
