// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LicensingService is the Wails-bound wrapper around the licensing.Manager.
 * It exposes tier management, feature gating, and per-agent metering to both
 * the frontend Settings > License page and to internal service guard checks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as licensing$0 from "../licensing/models.js";

/**
 * ActivateLicense verifies and activates a license token, persisting it to the
 * settings database. Returns an error string on failure.
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function ActivateLicense(token) {
    return $Call.ByID(623501635, token);
}

/**
 * ActiveAgentCount returns the current number of registered agents.
 * @returns {$CancellablePromise<number>}
 */
export function ActiveAgentCount() {
    return $Call.ByID(1218346651);
}

/**
 * DeactivateLicense removes the current license and reverts to Community tier.
 * @returns {$CancellablePromise<void>}
 */
export function DeactivateLicense() {
    return $Call.ByID(2952110962);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3842855920).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetFeatureMap returns the full map of features and their enabled state.
 * Used by the License page to render the feature matrix.
 * @returns {$CancellablePromise<{ [_ in string]?: boolean }>}
 */
export function GetFeatureMap() {
    return $Call.ByID(2480877163).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLicenseStatus returns the current license state for the frontend.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetLicenseStatus() {
    return $Call.ByID(1664549904).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsFeatureEnabled reports whether a named feature is available under the
 * current license. Used by the frontend to conditionally render gated UI.
 * @param {string} feature
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFeatureEnabled(feature) {
    return $Call.ByID(716854310, feature);
}

/**
 * Manager exposes the underlying licensing.Manager for use by other services.
 * @returns {$CancellablePromise<licensing$0.Manager | null>}
 */
export function Manager() {
    return $Call.ByID(3358244124).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(4233300342);
}

/**
 * RegisterAgent increments the live agent count and checks the license seat limit.
 * Returns an error if the agent limit would be exceeded.
 * @returns {$CancellablePromise<void>}
 */
export function RegisterAgent() {
    return $Call.ByID(2687606513);
}

/**
 * RequireFeature is a guard helper for internal service calls.
 * @param {licensing$0.Feature} f
 * @returns {$CancellablePromise<void>}
 */
export function RequireFeature(f) {
    return $Call.ByID(153472402, f);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(821646991);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(909308757);
}

/**
 * UnregisterAgent decrements the live agent count.
 * @returns {$CancellablePromise<void>}
 */
export function UnregisterAgent() {
    return $Call.ByID(172400960);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = licensing$0.Manager.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
