// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogSourceService exposes external log source management to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logsources$0 from "../logsources/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {logsources$0.LogSource} src
 * @returns {$CancellablePromise<void>}
 */
export function AddSource(src) {
    return $Call.ByID(356557660, src);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSavedSearch(id) {
    return $Call.ByID(1432162776, id);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3799787287).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportCSV returns query results as a CSV string
 * @param {string} sourceID
 * @param {string} query
 * @param {string} timeRange
 * @param {number} limit
 * @returns {$CancellablePromise<string>}
 */
export function ExportCSV(sourceID, query, timeRange, limit) {
    return $Call.ByID(1096359648, sourceID, query, timeRange, limit);
}

/**
 * ExportJSON returns query results as a JSON string
 * @param {string} sourceID
 * @param {string} query
 * @param {string} timeRange
 * @param {number} limit
 * @returns {$CancellablePromise<string>}
 */
export function ExportJSON(sourceID, query, timeRange, limit) {
    return $Call.ByID(4178455610, sourceID, query, timeRange, limit);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllTags() {
    return $Call.ByID(1988357392).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetHealthStatus returns current health for all configured sources
 * @returns {$CancellablePromise<$models.SourceHealth[]>}
 */
export function GetHealthStatus() {
    return $Call.ByID(2823356814).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LogSourceSavedSearch[]>}
 */
export function GetSavedSearches() {
    return $Call.ByID(2137266149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<logsources$0.LogSource[]>}
 */
export function GetSources() {
    return $Call.ByID(638748408).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} tag
 * @returns {$CancellablePromise<logsources$0.LogSource[]>}
 */
export function GetSourcesByTag(tag) {
    return $Call.ByID(3005988611, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1443586177);
}

/**
 * @param {string} sourceID
 * @param {string} query
 * @param {string} timeRange
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<logsources$0.LogResult[]>}
 */
export function QuerySource(sourceID, query, timeRange, limit, offset) {
    return $Call.ByID(6038635, sourceID, query, timeRange, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSource(id) {
    return $Call.ByID(314439891, id);
}

/**
 * @param {string} sourceID
 * @param {string} name
 * @param {string} query
 * @returns {$CancellablePromise<$models.LogSourceSavedSearch>}
 */
export function SaveSearch(sourceID, name, query) {
    return $Call.ByID(1490471143, sourceID, name, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SearchAllSources queries ALL enabled sources in parallel and merges results
 * @param {string} query
 * @param {string} timeRange
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<logsources$0.LogResult[]>}
 */
export function SearchAllSources(query, timeRange, limit, offset) {
    return $Call.ByID(3875480645, query, timeRange, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1195563138);
}

/**
 * @param {string} sourceID
 * @param {string} query
 * @returns {$CancellablePromise<void>}
 */
export function StartLokiStream(sourceID, query) {
    return $Call.ByID(1225252559, sourceID, query);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3256486402);
}

/**
 * @param {string} sourceID
 * @returns {$CancellablePromise<void>}
 */
export function StopLokiStream(sourceID) {
    return $Call.ByID(3614334031, sourceID);
}

/**
 * @param {string} sourceID
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<logsources$0.LogResult[]>}
 */
export function TailLoki(sourceID, query, limit) {
    return $Call.ByID(384364273, sourceID, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} sourceID
 * @returns {$CancellablePromise<$models.ConnectionResult>}
 */
export function TestConnection(sourceID) {
    return $Call.ByID(2049733150, sourceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.SourceHealth.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.LogSourceSavedSearch.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = logsources$0.LogSource.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = logsources$0.LogResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.ConnectionResult.createFrom;
