// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIResponse holds the result from an AI model
 */
export class AIResponse {
    /**
     * Creates a new AIResponse instance.
     * @param {Partial<AIResponse>} [$$source = {}] - The source object to create the AIResponse.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["raw_command"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIResponse(/** @type {Partial<AIResponse>} */($$parsedSource));
    }
}

/**
 * AgentDTO represents the UI model for an agent
 */
export class AgentDTO {
    /**
     * Creates a new AgentDTO instance.
     * @param {Partial<AgentDTO>} [$$source = {}] - The source object to create the AgentDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("last_seen" in $$source)) {
            /**
             * ISO8601 string
             * @member
             * @type {string}
             */
            this["last_seen"] = "";
        }
        if (!("remote_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote_address"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "online" | "offline"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("collectors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["collectors"] = [];
        }
        if (!("trust_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trust_level"] = "";
        }
        if (!("watchdog_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["watchdog_active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentDTO}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collectors" in $$parsedSource) {
            $$parsedSource["collectors"] = $$createField9_0($$parsedSource["collectors"]);
        }
        return new AgentDTO(/** @type {Partial<AgentDTO>} */($$parsedSource));
    }
}

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("window_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["window_width"] = 0;
        }
        if (!("window_height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["window_height"] = 0;
        }
        if (!("maximized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["maximized"] = false;
        }
        if (!("font_family" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["font_size"] = 0;
        }
        if (!("line_height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["line_height"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor_style"] = "";
        }
        if (!("cursor_blink" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cursor_blink"] = false;
        }
        if (!("scrollback_lines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scrollback_lines"] = 0;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("auto_lock_timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_lock_timeout"] = 0;
        }
        if (!("clipboard_clear" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clipboard_clear"] = 0;
        }
        if (!("log_sessions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["log_sessions"] = false;
        }
        if (!("keepalive_interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keepalive_interval"] = 0;
        }
        if (!("connection_timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connection_timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class BiasEntry {
    /**
     * Creates a new BiasEntry instance.
     * @param {Partial<BiasEntry>} [$$source = {}] - The source object to create the BiasEntry.
     */
    constructor($$source = {}) {
        if (!("anomaly_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["anomaly_id"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("evidence" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["evidence"] = [];
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * Operator who marked it
             * @member
             * @type {string}
             */
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiasEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiasEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField2_0($$parsedSource["evidence"]);
        }
        return new BiasEntry(/** @type {Partial<BiasEntry>} */($$parsedSource));
    }
}

/**
 * BookmarkCreateInput is the payload for creating a new bookmark.
 */
export class BookmarkCreateInput {
    /**
     * Creates a new BookmarkCreateInput instance.
     * @param {Partial<BookmarkCreateInput>} [$$source = {}] - The source object to create the BookmarkCreateInput.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_method"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["jump_host_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkCreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkCreateInput}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new BookmarkCreateInput(/** @type {Partial<BookmarkCreateInput>} */($$parsedSource));
    }
}

/**
 * BookmarkEntry is the frontend-friendly view of an SSH host bookmark.
 */
export class BookmarkEntry {
    /**
     * Creates a new BookmarkEntry instance.
     * @param {Partial<BookmarkEntry>} [$$source = {}] - The source object to create the BookmarkEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_method"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["credential_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["jump_host_id"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("is_favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }
        if (!("has_password" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_password"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_connected_at"] = undefined;
        }
        if (!("connection_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connection_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkEntry}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new BookmarkEntry(/** @type {Partial<BookmarkEntry>} */($$parsedSource));
    }
}

/**
 * CommandEntry represents a single command in the history.
 */
export class CommandEntry {
    /**
     * Creates a new CommandEntry instance.
     * @param {Partial<CommandEntry>} [$$source = {}] - The source object to create the CommandEntry.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["exit_code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandEntry(/** @type {Partial<CommandEntry>} */($$parsedSource));
    }
}

/**
 * CommandHistoryService stores and retrieves per-host command history.
 * Commands are stored in SQLite via the SIEM store's host event mechanism,
 * and are surfaced in the terminal autocomplete overlay.
 */
export class CommandHistoryService {
    /**
     * Creates a new CommandHistoryService instance.
     * @param {Partial<CommandHistoryService>} [$$source = {}] - The source object to create the CommandHistoryService.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandHistoryService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandHistoryService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandHistoryService(/** @type {Partial<CommandHistoryService>} */($$parsedSource));
    }
}

/**
 * ConnectionResult wraps test connection output for Wails
 */
export class ConnectionResult {
    /**
     * Creates a new ConnectionResult instance.
     * @param {Partial<ConnectionResult>} [$$source = {}] - The source object to create the ConnectionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionResult(/** @type {Partial<ConnectionResult>} */($$parsedSource));
    }
}

export class CredentialAnomaly {
    /**
     * Creates a new CredentialAnomaly instance.
     * @param {Partial<CredentialAnomaly>} [$$source = {}] - The source object to create the CredentialAnomaly.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["details"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialAnomaly instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialAnomaly}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialAnomaly(/** @type {Partial<CredentialAnomaly>} */($$parsedSource));
    }
}

/**
 * CredentialHealth represents the health status of a single credential
 */
export class CredentialHealth {
    /**
     * Creates a new CredentialHealth instance.
     * @param {Partial<CredentialHealth>} [$$source = {}] - The source object to create the CredentialHealth.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("age_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["age_days"] = 0;
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["issues"] = [];
        }
        if (!("score" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("severity" in $$source)) {
            /**
             * critical, warning, good
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialHealth}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField4_0($$parsedSource["issues"]);
        }
        return new CredentialHealth(/** @type {Partial<CredentialHealth>} */($$parsedSource));
    }
}

/**
 * DestructiveCheckResult holds the result of a safety analysis
 */
export class DestructiveCheckResult {
    /**
     * Creates a new DestructiveCheckResult instance.
     * @param {Partial<DestructiveCheckResult>} [$$source = {}] - The source object to create the DestructiveCheckResult.
     */
    constructor($$source = {}) {
        if (!("is_destructive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_destructive"] = false;
        }
        if (!("threats" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["threats"] = [];
        }
        if (!("severity" in $$source)) {
            /**
             * "low", "medium", "high", "critical"
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestructiveCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DestructiveCheckResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("threats" in $$parsedSource) {
            $$parsedSource["threats"] = $$createField1_0($$parsedSource["threats"]);
        }
        return new DestructiveCheckResult(/** @type {Partial<DestructiveCheckResult>} */($$parsedSource));
    }
}

/**
 * DiffItem represents a single file or directory difference
 */
export class DiffItem {
    /**
     * Creates a new DiffItem instance.
     * @param {Partial<DiffItem>} [$$source = {}] - The source object to create the DiffItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * 'missing_local', 'missing_remote', 'modified', 'identical'
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("local_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_size"] = 0;
        }
        if (!("remote_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remote_size"] = 0;
        }
        if (!("local_mod_time" in $$source)) {
            /**
             * unix timestamp
             * @member
             * @type {number}
             */
            this["local_mod_time"] = 0;
        }
        if (!("remote_mod_time" in $$source)) {
            /**
             * unix timestamp
             * @member
             * @type {number}
             */
            this["remote_mod_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffItem(/** @type {Partial<DiffItem>} */($$parsedSource));
    }
}

/**
 * DirectoryDiff holds the comparison result between a local and remote path
 */
export class DirectoryDiff {
    /**
     * Creates a new DirectoryDiff instance.
     * @param {Partial<DirectoryDiff>} [$$source = {}] - The source object to create the DirectoryDiff.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {DiffItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryDiff}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new DirectoryDiff(/** @type {Partial<DirectoryDiff>} */($$parsedSource));
    }
}

/**
 * EntityEnrichment holds geographic and threat context for an entity.
 */
export class EntityEnrichment {
    /**
     * Creates a new EntityEnrichment instance.
     * @param {Partial<EntityEnrichment>} [$$source = {}] - The source object to create the EntityEnrichment.
     */
    constructor($$source = {}) {
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("asn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["asn"] = "";
        }
        if (!("country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["country"] = "";
        }
        if (!("ioc_match" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ioc_match"] = false;
        }
        if (!("ioc_source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ioc_source"] = "";
        }
        if (!("ioc_desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ioc_desc"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntityEnrichment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntityEnrichment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntityEnrichment(/** @type {Partial<EntityEnrichment>} */($$parsedSource));
    }
}

/**
 * FileInfo represents a file on either a local or remote system
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("mod_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mod_time"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * HostAlert is a simplified alert for the operator banner.
 */
export class HostAlert {
    /**
     * Creates a new HostAlert instance.
     * @param {Partial<HostAlert>} [$$source = {}] - The source object to create the HostAlert.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("event_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event_type"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("source_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_ip"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostAlert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostAlert}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostAlert(/** @type {Partial<HostAlert>} */($$parsedSource));
    }
}

/**
 * IsolationStatus tracks the current containment state of a host.
 */
export class IsolationStatus {
    /**
     * Creates a new IsolationStatus instance.
     * @param {Partial<IsolationStatus>} [$$source = {}] - The source object to create the IsolationStatus.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("threat_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threat_score"] = 0;
        }
        if (!("isolated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["isolated_at"] = "";
        }
        if (!("auto" in $$source)) {
            /**
             * true = triggered by engine, false = manual
             * @member
             * @type {boolean}
             */
            this["auto"] = false;
        }
        if (!("rolled_back" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rolled_back"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IsolationStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IsolationStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IsolationStatus(/** @type {Partial<IsolationStatus>} */($$parsedSource));
    }
}

/**
 * LifecycleStats holds metrics from the last purge cycle
 */
export class LifecycleStats {
    /**
     * Creates a new LifecycleStats instance.
     * @param {Partial<LifecycleStats>} [$$source = {}] - The source object to create the LifecycleStats.
     */
    constructor($$source = {}) {
        if (!("last_run_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_run_at"] = "";
        }
        if (!("next_run_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next_run_at"] = "";
        }
        if (!("categories_purged" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["categories_purged"] = {};
        }
        if (!("total_rows_purged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_rows_purged"] = 0;
        }
        if (!("legal_hold_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["legal_hold_active"] = false;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecycleStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LifecycleStats}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories_purged" in $$parsedSource) {
            $$parsedSource["categories_purged"] = $$createField2_0($$parsedSource["categories_purged"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new LifecycleStats(/** @type {Partial<LifecycleStats>} */($$parsedSource));
    }
}

/**
 * LogSourceSavedSearch stores a reusable query per source
 */
export class LogSourceSavedSearch {
    /**
     * Creates a new LogSourceSavedSearch instance.
     * @param {Partial<LogSourceSavedSearch>} [$$source = {}] - The source object to create the LogSourceSavedSearch.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogSourceSavedSearch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogSourceSavedSearch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogSourceSavedSearch(/** @type {Partial<LogSourceSavedSearch>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * MultiExecJob tracks a multi-host execution job
 */
export class MultiExecJob {
    /**
     * Creates a new MultiExecJob instance.
     * @param {Partial<MultiExecJob>} [$$source = {}] - The source object to create the MultiExecJob.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("host_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["host_ids"] = [];
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {MultiExecResult[]}
             */
            this["results"] = [];
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ended_at"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "running", "completed", "partial"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MultiExecJob instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MultiExecJob}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("host_ids" in $$parsedSource) {
            $$parsedSource["host_ids"] = $$createField3_0($$parsedSource["host_ids"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField4_0($$parsedSource["results"]);
        }
        return new MultiExecJob(/** @type {Partial<MultiExecJob>} */($$parsedSource));
    }
}

/**
 * MultiExecResult holds the result from one host
 */
export class MultiExecResult {
    /**
     * Creates a new MultiExecResult instance.
     * @param {Partial<MultiExecResult>} [$$source = {}] - The source object to create the MultiExecResult.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("host_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_label"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("exit_code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exit_code"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["duration"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "success", "error", "timeout", "pending", "running"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MultiExecResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MultiExecResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MultiExecResult(/** @type {Partial<MultiExecResult>} */($$parsedSource));
    }
}

/**
 * OperatorContext is the security intelligence overlay for a terminal session.
 */
export class OperatorContext {
    /**
     * Creates a new OperatorContext instance.
     * @param {Partial<OperatorContext>} [$$source = {}] - The source object to create the OperatorContext.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("host_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_label"] = "";
        }
        if (!("risk_score" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["risk_score"] = 0;
        }
        if (!("risk_level" in $$source)) {
            /**
             * low, medium, high, critical
             * @member
             * @type {string}
             */
            this["risk_level"] = "";
        }
        if (!("alert_count" in $$source)) {
            /**
             * Active alerts for this host
             * @member
             * @type {number}
             */
            this["alert_count"] = 0;
        }
        if (!("recent_alerts" in $$source)) {
            /**
             * Last 5 alerts
             * @member
             * @type {HostAlert[]}
             */
            this["recent_alerts"] = [];
        }
        if (!("failed_logins" in $$source)) {
            /**
             * Last 24h
             * @member
             * @type {number}
             */
            this["failed_logins"] = 0;
        }
        if (!("suspicious_ips" in $$source)) {
            /**
             * Source IPs with failed logins
             * @member
             * @type {string[]}
             */
            this["suspicious_ips"] = [];
        }
        if (!("last_event" in $$source)) {
            /**
             * Timestamp of most recent SIEM event
             * @member
             * @type {string}
             */
            this["last_event"] = "";
        }
        if (!("threat_summary" in $$source)) {
            /**
             * One-line threat assessment
             * @member
             * @type {string}
             */
            this["threat_summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperatorContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperatorContext}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType9;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recent_alerts" in $$parsedSource) {
            $$parsedSource["recent_alerts"] = $$createField5_0($$parsedSource["recent_alerts"]);
        }
        if ("suspicious_ips" in $$parsedSource) {
            $$parsedSource["suspicious_ips"] = $$createField7_0($$parsedSource["suspicious_ips"]);
        }
        return new OperatorContext(/** @type {Partial<OperatorContext>} */($$parsedSource));
    }
}

/**
 * PersistedSession represents a saved session that can be restored.
 */
export class PersistedSession {
    /**
     * Creates a new PersistedSession instance.
     * @param {Partial<PersistedSession>} [$$source = {}] - The source object to create the PersistedSession.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("host_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_label"] = "";
        }
        if (!("tab_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tab_index"] = 0;
        }
        if (!("is_local" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_local"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistedSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersistedSession}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PersistedSession(/** @type {Partial<PersistedSession>} */($$parsedSource));
    }
}

/**
 * PersistedState is the full snapshot saved to disk.
 */
export class PersistedState {
    /**
     * Creates a new PersistedState instance.
     * @param {Partial<PersistedState>} [$$source = {}] - The source object to create the PersistedState.
     */
    constructor($$source = {}) {
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {PersistedSession[]}
             */
            this["sessions"] = [];
        }
        if (!("active_tab_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active_tab_index"] = 0;
        }
        if (!("saved_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saved_at"] = "";
        }
        if (!("app_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistedState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersistedState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        return new PersistedState(/** @type {Partial<PersistedState>} */($$parsedSource));
    }
}

export class PillarDrift {
    /**
     * Creates a new PillarDrift instance.
     * @param {Partial<PillarDrift>} [$$source = {}] - The source object to create the PillarDrift.
     */
    constructor($$source = {}) {
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("velocity" in $$source)) {
            /**
             * Points/hr
             * @member
             * @type {number}
             */
            this["velocity"] = 0;
        }
        if (!("trend" in $$source)) {
            /**
             * "Improving", "Stable", "Falling"
             * @member
             * @type {string}
             */
            this["trend"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PillarDrift instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PillarDrift}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PillarDrift(/** @type {Partial<PillarDrift>} */($$parsedSource));
    }
}

/**
 * RetentionPolicy defines TTL for a specific data category
 */
export class RetentionPolicy {
    /**
     * Creates a new RetentionPolicy instance.
     * @param {Partial<RetentionPolicy>} [$$source = {}] - The source object to create the RetentionPolicy.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("retain_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retain_days"] = 0;
        }
        if (!("archive_first" in $$source)) {
            /**
             * Archive to Parquet before purging
             * @member
             * @type {boolean}
             */
            this["archive_first"] = false;
        }
        if (!("is_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetentionPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RetentionPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetentionPolicy(/** @type {Partial<RetentionPolicy>} */($$parsedSource));
    }
}

/**
 * SecurityStats provides high-level metrics on identity hardening
 */
export class SecurityStats {
    /**
     * Creates a new SecurityStats instance.
     * @param {Partial<SecurityStats>} [$$source = {}] - The source object to create the SecurityStats.
     */
    constructor($$source = {}) {
        if (!("total_users" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_users"] = 0;
        }
        if (!("mfa_passive" in $$source)) {
            /**
             * Users with MFA enabled
             * @member
             * @type {number}
             */
            this["mfa_passive"] = 0;
        }
        if (!("rbac_active" in $$source)) {
            /**
             * True if custom roles are in use
             * @member
             * @type {boolean}
             */
            this["rbac_active"] = false;
        }
        if (!("mfa_enforcement" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mfa_enforcement"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SecurityStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityStats(/** @type {Partial<SecurityStats>} */($$parsedSource));
    }
}

/**
 * SessionPersistence saves and restores active terminal sessions across app restarts.
 * On graceful shutdown, it snapshots all active session host IDs and tab order.
 * On startup, it provides the saved state for re-connection.
 */
export class SessionPersistence {
    /**
     * Creates a new SessionPersistence instance.
     * @param {Partial<SessionPersistence>} [$$source = {}] - The source object to create the SessionPersistence.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionPersistence instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionPersistence}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionPersistence(/** @type {Partial<SessionPersistence>} */($$parsedSource));
    }
}

export class SnippetService {
    /**
     * Creates a new SnippetService instance.
     * @param {Partial<SnippetService>} [$$source = {}] - The source object to create the SnippetService.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnippetService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnippetService(/** @type {Partial<SnippetService>} */($$parsedSource));
    }
}

/**
 * SourceHealth tracks live connectivity status
 */
export class SourceHealth {
    /**
     * Creates a new SourceHealth instance.
     * @param {Partial<SourceHealth>} [$$source = {}] - The source object to create the SourceHealth.
     */
    constructor($$source = {}) {
        if (!("source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["healthy"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceHealth(/** @type {Partial<SourceHealth>} */($$parsedSource));
    }
}

export class TransferJob {
    /**
     * Creates a new TransferJob instance.
     * @param {Partial<TransferJob>} [$$source = {}] - The source object to create the TransferJob.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TransferType}
             */
            this["type"] = TransferType.$zero;
        }
        if (!("remote_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote_path"] = "";
        }
        if (!("local_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_path"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("total_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_bytes"] = 0;
        }
        if (!("bytes_copied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_copied"] = 0;
        }
        if (!("speed_bytes_s" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed_bytes_s"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TransferStatus}
             */
            this["status"] = TransferStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["completed_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferJob instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransferJob}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferJob(/** @type {Partial<TransferJob>} */($$parsedSource));
    }
}

/**
 * TransferProvider defines the interface for asynchronous file transfers.
 * @typedef {any} TransferProvider
 */

/**
 * @readonly
 * @enum {string}
 */
export const TransferStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusQueued: "queued",
    StatusInProgress: "in_progress",
    StatusCompleted: "completed",
    StatusFailed: "failed",
    StatusCancelled: "cancelled",
};

/**
 * @readonly
 * @enum {string}
 */
export const TransferType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TransferDownload: "download",
    TransferUpload: "upload",
};

export class TrustDriftMetrics {
    /**
     * Creates a new TrustDriftMetrics instance.
     * @param {Partial<TrustDriftMetrics>} [$$source = {}] - The source object to create the TrustDriftMetrics.
     */
    constructor($$source = {}) {
        if (!("current_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current_score"] = 0;
        }
        if (!("velocity_per_hour" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["velocity_per_hour"] = 0;
        }
        if (!("is_bleeding" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_bleeding"] = false;
        }
        if (!("estimated_failure_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["estimated_failure_time"] = "";
        }
        if (!("pillar_trends" in $$source)) {
            /**
             * @member
             * @type {PillarDrift[]}
             */
            this["pillar_trends"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrustDriftMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrustDriftMetrics}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pillar_trends" in $$parsedSource) {
            $$parsedSource["pillar_trends"] = $$createField4_0($$parsedSource["pillar_trends"]);
        }
        return new TrustDriftMetrics(/** @type {Partial<TrustDriftMetrics>} */($$parsedSource));
    }
}

export class TrustStatus {
    /**
     * Creates a new TrustStatus instance.
     * @param {Partial<TrustStatus>} [$$source = {}] - The source object to create the TrustStatus.
     */
    constructor($$source = {}) {
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "TRUSTED", "WARNING", "UNTRUSTED"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("last_check" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_check"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrustStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrustStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrustStatus(/** @type {Partial<TrustStatus>} */($$parsedSource));
    }
}

/**
 * TunnelInfo is the frontend-friendly tunnel representation
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "local", "remote", "dynamic"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("local_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_host"] = "";
        }
        if (!("local_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_port"] = 0;
        }
        if (!("remote_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote_host"] = "";
        }
        if (!("remote_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remote_port"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = DiffItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = MultiExecResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = HostAlert.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PersistedSession.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PillarDrift.createFrom;
const $$createType13 = $Create.Array($$createType12);
