// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkIsolatorService subscribes to ransomware isolation requests and
 * executes containment by applying firewall rules via the SSH/playbook layer.
 * It also exposes manual isolation/release controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dependencies returns service dependencies.
 * ssh-service and playbook-service must be ready before isolation commands can execute.
 * eventbus is infrastructure, not a kernel-managed service.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(824720993).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetIsolatedHosts returns all currently isolated hosts.
 * @returns {$CancellablePromise<$models.IsolationStatus[]>}
 */
export function GetIsolatedHosts() {
    return $Call.ByID(3951280414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsolateHost manually isolates a host from the frontend.
 * @param {string} hostID
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function IsolateHost(hostID, reason) {
    return $Call.ByID(1970543239, hostID, reason);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(652429583);
}

/**
 * ReleaseHost manually releases a host from isolation from the frontend.
 * @param {string} hostID
 * @returns {$CancellablePromise<void>}
 */
export function ReleaseHost(hostID) {
    return $Call.ByID(2289828227, hostID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3194646776);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3182287644);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.IsolationStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
