// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotesService handles host notes and runbooks operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

/**
 * DeleteNote deleting a note
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(1757162987, id);
}

/**
 * DeleteRunbook deletes a runbook
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRunbook(id) {
    return $Call.ByID(4286454369, id);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1909683725).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetNote returns a specific note
 * @param {string} id
 * @returns {$CancellablePromise<notes$0.Note | null>}
 */
export function GetNote(id) {
    return $Call.ByID(2298020312, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetNotes returns all notes for a host
 * @param {string} hostID
 * @returns {$CancellablePromise<notes$0.Note[]>}
 */
export function GetNotes(hostID) {
    return $Call.ByID(1258135601, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetRunbook returns a specific runbook
 * @param {string} id
 * @returns {$CancellablePromise<notes$0.Runbook | null>}
 */
export function GetRunbook(id) {
    return $Call.ByID(2486922444, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRunbooks returns runbooks for a host
 * @param {string} hostID
 * @returns {$CancellablePromise<notes$0.Runbook[]>}
 */
export function GetRunbooks(hostID) {
    return $Call.ByID(411840685, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(827262483);
}

/**
 * SaveNote saves a note
 * @param {notes$0.Note} note
 * @returns {$CancellablePromise<notes$0.Note | null>}
 */
export function SaveNote(note) {
    return $Call.ByID(2039884741, note).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveRunbook saves a runbook
 * @param {notes$0.Runbook} rb
 * @returns {$CancellablePromise<notes$0.Runbook | null>}
 */
export function SaveRunbook(rb) {
    return $Call.ByID(1187554199, rb).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Search searches across notes and runbooks
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function Search(query) {
    return $Call.ByID(3472443148, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3479494700);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(578027016);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = notes$0.Note.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = notes$0.Runbook.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
