// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ObservabilityService provides self-monitoring for OBLIVRA.
 * It exposes pprof endpoints, watches goroutine counts, and
 * detects potential deadlocks and resource anomalies.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3778843697).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetObservabilityStatus returns current system health metrics.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetObservabilityStatus() {
    return $Call.ByID(1510780079).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Name returns the service name.
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1475556191);
}

/**
 * Startup initialises pprof and starts background monitoring.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3181921576);
}

/**
 * Stop shuts down the pprof server, flushes OTel spans, and stops the watchdog.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(4055503884);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
