// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OperatorService provides the "Operator Mode" intelligence layer for the terminal.
 * It surfaces SIEM alerts, host risk scores, and anomaly data for the currently
 * active SSH session — enabling the operator to see security context without
 * leaving the terminal.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3207504444).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetBannerText returns a one-line status string for the terminal tab bar.
 * @param {string} hostID
 * @returns {$CancellablePromise<string>}
 */
export function GetBannerText(hostID) {
    return $Call.ByID(1082685102, hostID);
}

/**
 * GetContext returns the full security context for a host.
 * @param {string} hostID
 * @returns {$CancellablePromise<$models.OperatorContext | null>}
 */
export function GetContext(hostID) {
    return $Call.ByID(2394479034, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(955887546);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3241916147);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2967002689);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.OperatorContext.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
