// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlaybookService exposes automated response capabilities to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(105318779).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} action
 * @param {{ [_ in string]?: any }} params
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteAction(action, params) {
    return $Call.ByID(1963283607, action, params);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListAvailableActions() {
    return $Call.ByID(2617461656).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2263755613);
}

/**
 * @param {string} playbookID
 * @param {string} incidentID
 * @returns {$CancellablePromise<void>}
 */
export function RunPlaybook(playbookID, incidentID) {
    return $Call.ByID(215648408, playbookID, incidentID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1987704974);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(4032892758);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
