// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PolicyService exposes the Feature Governance Engine to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as policy$0 from "../policy/models.js";

/**
 * CheckFeature evaluates whether the given feature identifier is accessible
 * @param {string} feature
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckFeature(feature) {
    return $Call.ByID(3083519553, feature);
}

/**
 * DenyApproval rejects an approval request
 * @param {string} reqID
 * @param {string} denierID
 * @param {string} denierRole
 * @returns {$CancellablePromise<void>}
 */
export function DenyApproval(reqID, denierID, denierRole) {
    return $Call.ByID(2473535814, reqID, denierID, denierRole);
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1904738962).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * EvaluateMAC exposed for frontend UI components to proactively hide buttons if clearance is insufficient
 * @param {number} subjectClearance
 * @param {number} requiredClearance
 * @param {string} resource
 * @returns {$CancellablePromise<boolean>}
 */
export function EvaluateMAC(subjectClearance, requiredClearance, resource) {
    return $Call.ByID(3897622507, subjectClearance, requiredClearance, resource);
}

/**
 * GetActiveTier returns the current operation tier (e.g., free, pro, enterprise)
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveTier() {
    return $Call.ByID(2002176787);
}

/**
 * GetCapabilitiesMatrix returns all features and their evaluation status
 * @returns {$CancellablePromise<{ [_ in string]?: boolean }>}
 */
export function GetCapabilitiesMatrix() {
    return $Call.ByID(630955734).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPendingApprovals gets all waiting requests
 * @returns {$CancellablePromise<(policy$0.ApprovalRequest | null)[]>}
 */
export function GetPendingApprovals() {
    return $Call.ByID(2098395560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GrantApproval authorizes a pending request (requires admin simulation for the demo frontend)
 * @param {string} reqID
 * @param {string} approverID
 * @param {string} approverRole
 * @returns {$CancellablePromise<void>}
 */
export function GrantApproval(reqID, approverID, approverRole) {
    return $Call.ByID(1500396988, reqID, approverID, approverRole);
}

/**
 * Name returns the service name
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(368850612);
}

/**
 * RequestApproval initiates an Approval Chain for a destructive action.
 * @param {string} requesterID
 * @param {string} actionType
 * @param {string} targetResource
 * @returns {$CancellablePromise<policy$0.ApprovalRequest | null>}
 */
export function RequestApproval(requesterID, actionType, targetResource) {
    return $Call.ByID(2030503707, requesterID, actionType, targetResource).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetTier allows the frontend to simulate tier upgrades for demonstration purposes
 * @param {string} tier
 * @returns {$CancellablePromise<void>}
 */
export function SetTier(tier) {
    return $Call.ByID(3298621601, tier);
}

/**
 * Start is called at application startup
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(927782653);
}

/**
 * Stop is called at application termination
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1036571247);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = policy$0.ApprovalRequest.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
