// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordingService exposes recording features to frontend over Wails
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sharing$0 from "../sharing/models.js";

/**
 * DeleteRecording removes a recorded session
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRecording(id) {
    return $Call.ByID(222091800, id);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(775764227).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportRecording generates a signed export for a recording
 * @param {string} id
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportRecording(id, destPath) {
    return $Call.ByID(1240157031, id, destPath);
}

/**
 * GetRecordingFrames retrieves all frames for a specific recording
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetRecordingFrames(id) {
    return $Call.ByID(1809066067, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetRecordingMeta retrieves metadata for a specific recording
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetRecordingMeta(id) {
    return $Call.ByID(1983597708, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListRecordings fetches all completed local recordings
 * @returns {$CancellablePromise<sharing$0.RecordingMetadata[]>}
 */
export function ListRecordings() {
    return $Call.ByID(3270079046).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * NewRecordingService bounds the recording manager to the app context
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2955180949);
}

/**
 * SearchRecordings executes a forensic search across all sessions
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function SearchRecordings(query) {
    return $Call.ByID(3153400322, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2831156822);
}

/**
 * StartRecording starts a new recording
 * @param {string} sessionID
 * @param {string} hostLabel
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording(sessionID, hostLabel, cols, rows) {
    return $Call.ByID(3512474469, sessionID, hostLabel, cols, rows);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3934084350);
}

/**
 * StopRecording finishes the active recording
 * @param {string} sessionID
 * @returns {$CancellablePromise<sharing$0.RecordingMetadata | null>}
 */
export function StopRecording(sessionID) {
    return $Call.ByID(1734124781, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = sharing$0.RecordingMetadata.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Nullable($$createType3);
