// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as risk$0 from "../risk/models.js";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(941925803).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} type_
 * @param {string} target
 * @param {string[]} changes
 * @returns {$CancellablePromise<risk$0.RiskScore>}
 */
export function EvaluateManual(type_, target, changes) {
    return $Call.ByID(2154306875, type_, target, changes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<risk$0.RiskScore[]>}
 */
export function GetRiskHistory() {
    return $Call.ByID(1447237507).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1677171853);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3677638558);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3390310054);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = risk$0.RiskScore.createFrom;
const $$createType2 = $Create.Array($$createType1);
