// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(4258202982).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<database$0.RotationPolicy[]>}
 */
export function ListPolicies() {
    return $Call.ByID(1501065641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(682743248);
}

/**
 * @param {string} credID
 * @param {number} frequencyDays
 * @param {boolean} notifyOnly
 * @returns {$CancellablePromise<string>}
 */
export function RegisterPolicy(credID, frequencyDays, notifyOnly) {
    return $Call.ByID(871459920, credID, frequencyDays, notifyOnly);
}

/**
 * @param {string} credID
 * @returns {$CancellablePromise<void>}
 */
export function RotateCredential(credID) {
    return $Call.ByID(802068073, credID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2755215753);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3600675619);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = database$0.RotationPolicy.createFrom;
const $$createType2 = $Create.Array($$createType1);
