// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CalculateTrustIndex computes the global 0.0 - 100.0 health score.
 * @returns {$CancellablePromise<number>}
 */
export function CalculateTrustIndex() {
    return $Call.ByID(1890185335);
}

/**
 * Dependencies returns service dependencies.
 * vault must be ready before trust checks run. attestation is wired at construction,
 * not a kernel-managed service. eventbus is infrastructure, not a service.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1395325030).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TrustStatus[]>}
 */
export function GetAggregatedStatus() {
    return $Call.ByID(457224334).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPillarScores computes the individual health scores for the 5 sovereign pillars.
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetPillarScores() {
    return $Call.ByID(1840684766).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTrustDriftMetrics returns the current trend, predicting failure if dropping.
 * @returns {$CancellablePromise<$models.TrustDriftMetrics>}
 */
export function GetTrustDriftMetrics() {
    return $Call.ByID(3318018745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1223583952);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1670687369);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(4141516323);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function VerifyIntegrity() {
    return $Call.ByID(266589605);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.TrustStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.TrustDriftMetrics.createFrom;
