// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService exposes security features to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as security$0 from "../security/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

/**
 * CheckSSHCertExpiry returns certs expiring in a certain number of hours
 * @param {number} hours
 * @returns {$CancellablePromise<ssh$0.CertificateInfo[]>}
 */
export function CheckSSHCertExpiry(hours) {
    return $Call.ByID(4055171424, hours).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1498387138).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FIDO2BeginRegistration starts the process
 * @param {string} userID
 * @param {string} userName
 * @returns {$CancellablePromise<security$0.FIDO2Challenge | null>}
 */
export function FIDO2BeginRegistration(userID, userName) {
    return $Call.ByID(4280835845, userID, userName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * FIDO2HasCredentials checks if any keys are enrolled
 * @returns {$CancellablePromise<boolean>}
 */
export function FIDO2HasCredentials() {
    return $Call.ByID(816268349);
}

/**
 * FIDO2ListCredentials returns enrolled keys
 * @returns {$CancellablePromise<security$0.FIDO2Credential[]>}
 */
export function FIDO2ListCredentials() {
    return $Call.ByID(1304816659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * FIDO2RemoveCredential removes an enrolled key
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function FIDO2RemoveCredential(id) {
    return $Call.ByID(2135650918, id);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(207258404);
}

/**
 * QuorumApprove records an approval. challengeID is a FIDO2 challenge issued
 * via FIDO2Manager.StartAuthentication before the user signed; the underlying
 * QuorumManager.Approve drives FIDO2Manager.CompleteAuthentication so the
 * hardware signature is verified before the approval is counted.
 * @param {string} id
 * @param {string} userID
 * @param {string} challengeID
 * @param {string} credentialID
 * @param {string} signature
 * @param {string} authData
 * @param {string} clientData
 * @param {number} newSignCount
 * @returns {$CancellablePromise<void>}
 */
export function QuorumApprove(id, userID, challengeID, credentialID, signature, authData, clientData, newSignCount) {
    return $Call.ByID(2158832195, id, userID, challengeID, credentialID, signature, authData, clientData, newSignCount);
}

/**
 * QuorumGetRequest retrieves a specific request
 * @param {string} id
 * @returns {$CancellablePromise<security$0.QuorumRequest | null>}
 */
export function QuorumGetRequest(id) {
    return $Call.ByID(2794850491, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * QuorumListPending returns all pending requests
 * @returns {$CancellablePromise<(security$0.QuorumRequest | null)[]>}
 */
export function QuorumListPending() {
    return $Call.ByID(3523835449).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * QuorumPropose starts a new M-of-N approval ceremony
 * @param {string} action
 * @param {string} description
 * @param {string} proposer
 * @param {number} required
 * @param {string} payload
 * @returns {$CancellablePromise<security$0.QuorumRequest | null>}
 */
export function QuorumPropose(action, description, proposer, required, payload) {
    return $Call.ByID(3681657504, action, description, proposer, required, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<ssh$0.CertificateInfo[]>}
 */
export function SSHListCertificates() {
    return $Call.ByID(1650054559).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2440197069);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1861616767);
}

/**
 * YubiKeyDeriveVaultKey performs a challenge-response with the YubiKey to get the hardware key segment
 * @param {string} serial
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function YubiKeyDeriveVaultKey(serial, password) {
    return $Call.ByID(3650831743, serial, password).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * YubiKeyDetect lists connected YubiKeys
 * @returns {$CancellablePromise<security$0.YubiKeyInfo[]>}
 */
export function YubiKeyDetect() {
    return $Call.ByID(3861275372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * YubiKeyGenerateSSHKey provisions a new SSH key on the YubiKey
 * @param {string} serial
 * @param {string} slot
 * @param {string} pin
 * @returns {$CancellablePromise<string>}
 */
export function YubiKeyGenerateSSHKey(serial, slot, pin) {
    return $Call.ByID(3145140645, serial, slot, pin);
}

/**
 * YubiKeyGetSSHPublicKey gets the public key material
 * @param {string} serial
 * @param {string} slot
 * @returns {$CancellablePromise<string>}
 */
export function YubiKeyGetSSHPublicKey(serial, slot) {
    return $Call.ByID(3585324875, serial, slot);
}

// Private type creation functions
const $$createType0 = ssh$0.CertificateInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = security$0.FIDO2Challenge.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = security$0.FIDO2Credential.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = security$0.QuorumRequest.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = security$0.YubiKeyInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
