// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionPersistence saves and restores active terminal sessions across app restarts.
 * On graceful shutdown, it snapshots all active session host IDs and tab order.
 * On startup, it provides the saved state for re-connection.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearState removes the persisted state file (e.g., after successful restore).
 * @returns {$CancellablePromise<void>}
 */
export function ClearState() {
    return $Call.ByID(1303864303);
}

/**
 * GetRestorable returns the host IDs and labels that can be restored.
 * Used by the frontend to show "Restore previous sessions?" prompt.
 * @returns {$CancellablePromise<$models.PersistedSession[]>}
 */
export function GetRestorable() {
    return $Call.ByID(3598113584).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * HasState returns true if there's a persisted state file to restore.
 * @returns {$CancellablePromise<boolean>}
 */
export function HasState() {
    return $Call.ByID(3319040764);
}

/**
 * LoadState reads the persisted session state from disk.
 * Returns nil state if no state file exists (first launch).
 * @returns {$CancellablePromise<$models.PersistedState | null>}
 */
export function LoadState() {
    return $Call.ByID(1976235506).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SaveState persists the current active sessions to disk.
 * Called on graceful app shutdown (SSHService.Stop).
 * @param {$models.PersistedSession[]} sessions
 * @param {number} activeTabIdx
 * @returns {$CancellablePromise<void>}
 */
export function SaveState(sessions, activeTabIdx) {
    return $Call.ByID(1440999285, sessions, activeTabIdx);
}

// Private type creation functions
const $$createType0 = $models.PersistedSession.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PersistedState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
