// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SIEMService exposes SIEM configurations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oql$0 from "../oql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as threatintel$0 from "../threatintel/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AggregateHostEvents exposes the Bleve/SQL facet aggregation capability to the UI
 * @param {string} query
 * @param {string} facetField
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function AggregateHostEvents(query, facetField) {
    return $Call.ByID(415399265, query, facetField).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AnalyzeEvent uses AI to analyze a specific log entry
 * @param {string} rawLog
 * @returns {$CancellablePromise<$models.AIResponse | null>}
 */
export function AnalyzeEvent(rawLog) {
    return $Call.ByID(3642783707, rawLog).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Configure changes the forwarding destination
 * @param {boolean} enabled
 * @param {string} destination
 * @param {string} url
 * @param {string} token
 * @param {number} batchSize
 * @returns {$CancellablePromise<void>}
 */
export function Configure(enabled, destination, url, token, batchSize) {
    return $Call.ByID(1775870473, enabled, destination, url, token, batchSize);
}

/**
 * CreateSavedSearch persists a given query so the user can recall it later
 * @param {database$0.SavedSearch | null} search
 * @returns {$CancellablePromise<void>}
 */
export function CreateSavedSearch(search) {
    return $Call.ByID(1733936098, search);
}

/**
 * Dependencies returns service dependencies.
 * eventbus is infrastructure wired at construction time, not a kernel-managed service.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2370199122).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ExecuteOQL parses and executes a Sovereign Query Language string
 * @param {string} query
 * @returns {$CancellablePromise<oql$0.QueryResult | null>}
 */
export function ExecuteOQL(query) {
    return $Call.ByID(1439642994, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetEventTrend returns security event counts over time
 * @param {number} days
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetEventTrend(days) {
    return $Call.ByID(3492866178, days).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetFailedLoginsByHost fetches aggregated login failure analytics for the ThreatMap ECharts visualization
 * @param {string} hostID
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetFailedLoginsByHost(hostID) {
    return $Call.ByID(1222120141, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetGlobalThreatStats aggregates security data across all hosts for the Dashboard KPIs
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetGlobalThreatStats() {
    return $Call.ByID(3463531621).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetHostEvents grabs raw parsed anomalies mapped to a specific internal SSH server UUID
 * @param {string} hostID
 * @param {number} limit
 * @returns {$CancellablePromise<database$0.HostEvent[]>}
 */
export function GetHostEvents(hostID, limit) {
    return $Call.ByID(1860266734, hostID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetRiskScoreByHost calculates a 0-100 score of how compromised this host might be
 * @param {string} hostID
 * @returns {$CancellablePromise<number>}
 */
export function GetRiskScoreByHost(hostID) {
    return $Call.ByID(3524066747, hostID);
}

/**
 * GetSavedSearches retrieves all persisted SIEM queries
 * @returns {$CancellablePromise<database$0.SavedSearch[]>}
 */
export function GetSavedSearches() {
    return $Call.ByID(754213768).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetThreatIntelStats returns matcher statistics for the Threat Intel dashboard
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetThreatIntelStats() {
    return $Call.ByID(3769420266).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LoadOfflineIOCs provides an endpoint for the UI to inject new offline observables
 * @param {threatintel$0.Indicator[]} indicators
 * @returns {$CancellablePromise<number>}
 */
export function LoadOfflineIOCs(indicators) {
    return $Call.ByID(1079167084, indicators);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(3755365236);
}

/**
 * SearchHostEvents performs a global search across all host anomaly events
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<database$0.HostEvent[]>}
 */
export function SearchHostEvents(query, limit) {
    return $Call.ByID(193127032, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1433403581);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(86645039);
}

/**
 * @returns {$CancellablePromise<database$0.SIEMStore>}
 */
export function Store() {
    return $Call.ByID(2001362832);
}

/**
 * TestConnection pushes a test event
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection() {
    return $Call.ByID(2155056883);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.AIResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = oql$0.QueryResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = database$0.HostEvent.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = database$0.SavedSearch.createFrom;
const $$createType11 = $Create.Array($$createType10);
