// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService manages SSH connections and sessions
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTransfer aborts a background sync
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function CancelTransfer(jobID) {
    return $Call.ByID(2846404630, jobID);
}

/**
 * ClearTransfers cleans up the transfer queue
 * @returns {$CancellablePromise<void>}
 */
export function ClearTransfers() {
    return $Call.ByID(2921525764);
}

/**
 * CloseAll closes all SSH sessions
 * @returns {$CancellablePromise<void>}
 */
export function CloseAll() {
    return $Call.ByID(3004107792);
}

/**
 * CompareDirectories compares a local and remote directory and returns the differences
 * @param {string} ctxID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<$models.DirectoryDiff | null>}
 */
export function CompareDirectories(ctxID, localPath, remotePath) {
    return $Call.ByID(2092689581, ctxID, localPath, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Connect establishes an SSH connection to a host using a centralized session lifecycle.
 * @param {string} hostID
 * @returns {$CancellablePromise<string>}
 */
export function Connect(hostID) {
    return $Call.ByID(441253959, hostID);
}

/**
 * ConnectToSession is a tactical variant of Connect that uses a pre-defined session ID.
 * @param {string} hostID
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function ConnectToSession(hostID, sessionID) {
    return $Call.ByID(430508438, hostID, sessionID);
}

/**
 * Dependencies returns service dependencies.
 * Note: eventbus is infrastructure wired at construction time, not a kernel-managed service.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1225364862).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeployKey generates a local SSH key and deploys it to the remote host
 * @param {string} hostID
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function DeployKey(hostID, password) {
    return $Call.ByID(415996455, hostID, password);
}

/**
 * Exec runs a non-interactive command on an active session and returns output
 * @param {string} sessionID
 * @param {string} cmd
 * @returns {$CancellablePromise<string>}
 */
export function Exec(sessionID, cmd) {
    return $Call.ByID(3790446902, sessionID, cmd);
}

/**
 * ExecWithStdin runs a non-interactive command and pipes the given string to its stdin.
 * @param {string} sessionID
 * @param {string} cmd
 * @param {string} stdin
 * @returns {$CancellablePromise<string>}
 */
export function ExecWithStdin(sessionID, cmd, stdin) {
    return $Call.ByID(827215744, sessionID, cmd, stdin);
}

/**
 * GetActiveSessionForHost returns the first active SSH session ID for a given hostID.
 * Implements isolation.HostSessionResolver so NetworkIsolator can execute remote commands.
 * @param {string} hostID
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function GetActiveSessionForHost(hostID) {
    return $Call.ByID(183315990, hostID);
}

/**
 * GetActiveSessions returns all active session IDs
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetActiveSessions() {
    return $Call.ByID(3803078486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSession implements SessionProvider
 * @param {string} id
 * @returns {$CancellablePromise<[ssh$0.Session | null, boolean]>}
 */
export function GetSession(id) {
    return $Call.ByID(3701662255, id).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType6($result[0]);
        return $result;
    }));
}

/**
 * GetTransferState returns all active/recent transfers
 * @returns {$CancellablePromise<$models.TransferJob[]>}
 */
export function GetTransferState() {
    return $Call.ByID(3750727155).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ImportSSHConfig imports hosts from ~/.ssh/config
 * @returns {$CancellablePromise<ssh$0.SSHConfigEntry[]>}
 */
export function ImportSSHConfig() {
    return $Call.ByID(416335774).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListDirectory returns the contents of a directory on the remote host via SFTP
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(ctxID, path) {
    return $Call.ByID(975099002, ctxID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * Mkdir creates a new directory on the remote host
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(ctxID, path) {
    return $Call.ByID(1174824994, ctxID, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1220769144);
}

/**
 * PushCredential fetches a secret from the vault and injects it into the session's stdin
 * @param {string} sessionID
 * @param {string} credentialID
 * @returns {$CancellablePromise<void>}
 */
export function PushCredential(sessionID, credentialID) {
    return $Call.ByID(3354772334, sessionID, credentialID);
}

/**
 * ReadFile downloads a file from the remote host and returns its base64 encoded content
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(ctxID, path) {
    return $Call.ByID(300929241, ctxID, path);
}

/**
 * Remove deletes a file or directory (must be empty) on the remote host
 * @param {string} ctxID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Remove(ctxID, path) {
    return $Call.ByID(1732892447, ctxID, path);
}

/**
 * Rename renames or moves a file/directory on the remote host
 * @param {string} ctxID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function Rename(ctxID, oldPath, newPath) {
    return $Call.ByID(2944164297, ctxID, oldPath, newPath);
}

/**
 * Resize changes the terminal dimensions for a session
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(534323019, sessionID, cols, rows);
}

/**
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SendInput(sessionID, data) {
    return $Call.ByID(249215675, sessionID, data);
}

/**
 * @param {$models.CommandHistoryService | null} svc
 * @returns {$CancellablePromise<void>}
 */
export function SetCommandHistory(svc) {
    return $Call.ByID(4042335446, svc);
}

/**
 * @param {$models.SessionPersistence | null} svc
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionPersistence(svc) {
    return $Call.ByID(3660101958, svc);
}

/**
 * @param {$models.SnippetService | null} svc
 * @returns {$CancellablePromise<void>}
 */
export function SetSnippetService(svc) {
    return $Call.ByID(761427985, svc);
}

/**
 * @param {$models.TransferProvider} tm
 * @returns {$CancellablePromise<void>}
 */
export function SetTransferManager(tm) {
    return $Call.ByID(1121737721, tm);
}

/**
 * SftpChmod changes the permissions of a file on the remote host
 * @param {string} ctxID
 * @param {string} path
 * @param {number} mode
 * @returns {$CancellablePromise<void>}
 */
export function SftpChmod(ctxID, path, mode) {
    return $Call.ByID(2656857331, ctxID, path, mode);
}

/**
 * SftpDownloadAsync queues a file transfer to background worker
 * @param {string} sessionID
 * @param {string} remotePath
 * @param {string} localPath
 * @param {number} fileSize
 * @returns {$CancellablePromise<string>}
 */
export function SftpDownloadAsync(sessionID, remotePath, localPath, fileSize) {
    return $Call.ByID(1339595154, sessionID, remotePath, localPath, fileSize);
}

/**
 * SftpUploadAsync queues a file transfer to background worker
 * @param {string} sessionID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function SftpUploadAsync(sessionID, localPath, remotePath) {
    return $Call.ByID(414087245, sessionID, localPath, remotePath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1740158529);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1740771003);
}

/**
 * WriteFile uploads a base64 encoded string to the remote file path
 * @param {string} ctxID
 * @param {string} path
 * @param {string} contentBase64
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(ctxID, path, contentBase64) {
    return $Call.ByID(2929294592, ctxID, path, contentBase64);
}

// Private type creation functions
const $$createType0 = $models.DirectoryDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ssh$0.Session.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.TransferJob.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ssh$0.SSHConfigEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.FileInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
