// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

/**
 * @param {database$0.SuppressionRule | null} rule
 * @returns {$CancellablePromise<string>}
 */
export function CreateRule(rule) {
    return $Call.ByID(1037381000, rule);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(id) {
    return $Call.ByID(3113210371, id);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1329322119).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<database$0.SuppressionRule[]>}
 */
export function ListRules() {
    return $Call.ByID(609072713).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * MatchCount returns the number of alerts a given rule has silenced since
 * process start. Resets on restart by design — durable counts would require
 * a schema column we don't have yet (Phase 26.9 follow-up).
 * @param {string} ruleID
 * @returns {$CancellablePromise<number>}
 */
export function MatchCount(ruleID) {
    return $Call.ByID(1142585354, ruleID);
}

/**
 * MatchCounts returns a snapshot map of all in-memory match counts.
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function MatchCounts() {
    return $Call.ByID(2930484859).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(3893892977);
}

/**
 * ShouldSuppress checks if an alert with the given metadata should be silenced.
 * @param {string} ruleID
 * @param {{ [_ in string]?: string }} metadata
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ShouldSuppress(ruleID, metadata) {
    return $Call.ByID(412311662, ruleID, metadata);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(63322578);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2822817938);
}

/**
 * SuggestFromEvidence builds a draft suppression rule from a false-positive
 * evidence map. Looks at common fields (host_id, user_name, src_ip,
 * rule_id, event_type) and prefers the most specific match.
 * 
 * The returned rule is a draft — ID/CreatedAt are unset so the caller can
 * either present it to an operator for approval (preferred) or call
 * CreateRule directly. Phase 26.9's "automated feedback loop" — feedback
 * (mark-as-FP) generates a suggestion, which the operator can promote to
 * a suppression rule with one click.
 * @param {{ [_ in string]?: any }[]} evidence
 * @returns {$CancellablePromise<database$0.SuppressionRule | null>}
 */
export function SuggestFromEvidence(evidence) {
    return $Call.ByID(3469646581, evidence).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @param {boolean} active
 * @returns {$CancellablePromise<void>}
 */
export function ToggleRule(id, active) {
    return $Call.ByID(3678653156, id, active);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = database$0.SuppressionRule.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Nullable($$createType1);
