// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TailingService aggregates output from multiple SSH sessions for a unified feed
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2251279722).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1207051292);
}

/**
 * RegisterOutput processes raw output from a session and emits a TailEvent
 * @param {string} sessionID
 * @param {string} hostLabel
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function RegisterOutput(sessionID, hostLabel, data) {
    return $Call.ByID(4185112915, sessionID, hostLabel, data);
}

/**
 * SetCallback registers a handler for aggregated tail events (e.g. for UI streaming)
 * @param {any} cb
 * @returns {$CancellablePromise<void>}
 */
export function SetCallback(cb) {
    return $Call.ByID(56469926, cb);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(277786837);
}

/**
 * StartTailing adds a session to the aggregation feed
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StartTailing(sessionID) {
    return $Call.ByID(1599662501, sessionID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3729545575);
}

/**
 * StopAll clears the tailing list
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(849785026);
}

/**
 * StopTailing removes a session from the aggregation feed
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StopTailing(sessionID) {
    return $Call.ByID(2019201443, sessionID);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
