// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TeamService exposes team vault operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as team$0 from "../team/models.js";

/**
 * AddMember adds a user to the team vault
 * @param {string} email
 * @param {string} name
 * @param {string} roleStr
 * @returns {$CancellablePromise<team$0.TeamMember | null>}
 */
export function AddMember(email, name, roleStr) {
    return $Call.ByID(2274975701, email, name, roleStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AddSecret saves an encrypted value
 * @param {string} title
 * @param {string} entryType
 * @param {string} secretData
 * @returns {$CancellablePromise<team$0.VaultEntry | null>}
 */
export function AddSecret(title, entryType, secretData) {
    return $Call.ByID(4209034863, title, entryType, secretData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1382637513).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSecret reads a shared value
 * @param {string} entryID
 * @returns {$CancellablePromise<string>}
 */
export function GetSecret(entryID) {
    return $Call.ByID(1312151140, entryID);
}

/**
 * GetTeamName gets the vault name
 * @returns {$CancellablePromise<string>}
 */
export function GetTeamName() {
    return $Call.ByID(2683383642);
}

/**
 * ListActivity returns recent team events
 * @returns {$CancellablePromise<team$0.TeamActivity[]>}
 */
export function ListActivity() {
    return $Call.ByID(1111411689).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListMembers gets team users
 * @returns {$CancellablePromise<team$0.TeamMember[]>}
 */
export function ListMembers() {
    return $Call.ByID(532718351).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListSecrets returns metadata for all accessible items
 * @returns {$CancellablePromise<team$0.VaultEntry[]>}
 */
export function ListSecrets() {
    return $Call.ByID(2787295921).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(425903687);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetActorID(id) {
    return $Call.ByID(3779839208, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1144167552);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2552738884);
}

// Private type creation functions
const $$createType0 = team$0.TeamMember.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = team$0.VaultEntry.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = team$0.TeamActivity.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $Create.Array($$createType2);
