// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TelemetryService exposes real-time host system metrics to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitoring$0 from "../monitoring/models.js";

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(606901595).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetFleetTelemetry returns metrics for all hosts currently being monitored
 * @returns {$CancellablePromise<monitoring$0.HostTelemetry[]>}
 */
export function GetFleetTelemetry() {
    return $Call.ByID(205064141).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetHostTelemetry returns the latest metrics for a specific host
 * @param {string} hostID
 * @returns {$CancellablePromise<[monitoring$0.HostTelemetry, boolean]>}
 */
export function GetHostTelemetry(hostID) {
    return $Call.ByID(3466723059, hostID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * NewTelemetryService creates a new TelemetryService
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1176652349);
}

/**
 * Startup is called at application startup
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2042513134);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2987366198);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = monitoring$0.HostTelemetry.createFrom;
const $$createType2 = $Create.Array($$createType1);
