// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemporalService exposes temporal integrity capabilities to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as temporal$0 from "../temporal/models.js";

/**
 * CheckSequenceManipulation scans events for timestamp inversions.
 * @param {temporal$0.TimestampedEvent[]} events
 * @returns {$CancellablePromise<temporal$0.SequenceAnomaly[]>}
 */
export function CheckSequenceManipulation(events) {
    return $Call.ByID(3747287729, events).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2345400678).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAgentDrift returns the latest clock drift readings per agent.
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetAgentDrift() {
    return $Call.ByID(695171597).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetFleetDriftReport returns statistical analysis of fleet-wide clock drift.
 * @returns {$CancellablePromise<temporal$0.FleetDriftReport | null>}
 */
export function GetFleetDriftReport() {
    return $Call.ByID(1742233464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetViolations returns all recorded temporal violations.
 * @returns {$CancellablePromise<temporal$0.Violation[]>}
 */
export function GetViolations() {
    return $Call.ByID(3691235889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(3847506384);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2549472649);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2470471459);
}

// Private type creation functions
const $$createType0 = temporal$0.SequenceAnomaly.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = temporal$0.FleetDriftReport.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = temporal$0.Violation.createFrom;
const $$createType7 = $Create.Array($$createType6);
