// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAll stops all tunnels
 * @returns {$CancellablePromise<void>}
 */
export function CloseAll() {
    return $Call.ByID(296632516);
}

/**
 * CloseAllForSession closes all tunnels for a session
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseAllForSession(sessionID) {
    return $Call.ByID(2631456645, sessionID);
}

/**
 * CreateTunnel creates and starts a port forwarding tunnel
 * @param {ssh$0.Client | null} client
 * @param {string} sessionID
 * @param {string} tunnelType
 * @param {string} localHost
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function CreateTunnel(client, sessionID, tunnelType, localHost, localPort, remoteHost, remotePort) {
    return $Call.ByID(530540329, client, sessionID, tunnelType, localHost, localPort, remoteHost, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(2208217162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAll returns all tunnels
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function GetAll() {
    return $Call.ByID(2649166080).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetBySession returns tunnels for a specific session
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function GetBySession(sessionID) {
    return $Call.ByID(3763663572, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(816553980);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1657199669);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3763608903);
}

/**
 * StopTunnel stops a tunnel
 * @param {string} tunnelID
 * @returns {$CancellablePromise<void>}
 */
export function StopTunnel(tunnelID) {
    return $Call.ByID(1589562121, tunnelID);
}

// Private type creation functions
const $$createType0 = $models.TunnelInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
