// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UEBAService exposes behavioral analytics to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ueba$0 from "../ueba/models.js";

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(3697230919).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetProfiles returns the current behavioral profiles.
 * @returns {$CancellablePromise<(ueba$0.EntityProfile | null)[]>}
 */
export function GetProfiles() {
    return $Call.ByID(3662729800).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(2642661681);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3738621330);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1571586642);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ueba$0.EntityProfile.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
