// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService exposes application update functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ApplyUpdate downloads and applies the latest update
 * @returns {$CancellablePromise<void>}
 */
export function ApplyUpdate() {
    return $Call.ByID(1655205321);
}

/**
 * CheckForUpdate checks if a newer version is available
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2214498050).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateOfflineBundle packages the current binary into a signed update for air-gapped nodes
 * @param {string} outputDir
 * @returns {$CancellablePromise<string>}
 */
export function CreateOfflineBundle(outputDir) {
    return $Call.ByID(2384007423, outputDir);
}

/**
 * Dependencies returns service dependencies
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1189462385).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportOfflineBundle applies a signed update from a local file path (USB/Physical media)
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ImportOfflineBundle(path) {
    return $Call.ByID(3339849780, path);
}

/**
 * Name returns the service name
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(1635684767);
}

/**
 * Startup is called at application startup
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2639995496);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(4173952588);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
