// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService is a Wails-bound service that lets the frontend pop a panel
 * out into its own native window — the SOC operator pattern of "drag the
 * SIEM search to monitor 2, drag the alerts board to monitor 3, keep the
 * terminal on monitor 1." Each pop-out is a real Wails window backed by the
 * same Go process and the same in-memory data, so there's zero IPC round
 * trip between the panel views.
 * 
 * SOC multi-monitor support.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseAllPopouts is a convenience for "reset my workspace" — closes every
 * pop-out without touching the main window. Useful when an operator has 7
 * windows scattered across 4 monitors and wants to start over.
 * @returns {$CancellablePromise<number>}
 */
export function CloseAllPopouts() {
    return $Call.ByID(2216700548);
}

/**
 * ClosePopout closes a previously-opened pop-out window by ID. Idempotent —
 * returns nil if the ID was already closed/unknown.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ClosePopout(id) {
    return $Call.ByID(2708640154, id);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(4264586000).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListPopouts returns IDs of currently-tracked pop-outs. Stale entries
 * (windows the user closed via OS chrome) may persist until ClosePopout
 * is called explicitly — Wails v3 doesn't expose a portable "is this
 * window still alive" check we trust enough to use here.
 * @returns {$CancellablePromise<number[]>}
 */
export function ListPopouts() {
    return $Call.ByID(3741219769).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(153293974);
}

/**
 * PopOut spawns a new Wails window pointed at the given route. Always
 * creates a new window — multiple pop-outs of the same route are a valid
 * SOC pattern (e.g. one filtered to host A on monitor 2, another filtered
 * to host B on monitor 3).
 * 
 * The new window starts at "/?popout=1&route=<route>"; App.svelte detects
 * the popout query param to hide the sidebar and render only the requested
 * route.
 * 
 * Returns the integer window ID, which the caller can later pass to
 * FocusPopout(id) or ClosePopout(id).
 * @param {string} route
 * @param {string} title
 * @returns {$CancellablePromise<number>}
 */
export function PopOut(route, title) {
    return $Call.ByID(926275524, route, title);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(272430895);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1548727157);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
