// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService handles workspace related operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../workspace/models.js";

/**
 * Activate switches to the specified workspace
 * @param {string} id
 * @returns {$CancellablePromise<workspace$0.Workspace | null>}
 */
export function Activate(id) {
    return $Call.ByID(2288453109, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Create creates a new workspace
 * @param {string} name
 * @param {string} description
 * @param {string} icon
 * @returns {$CancellablePromise<workspace$0.Workspace | null>}
 */
export function Create(name, description, icon) {
    return $Call.ByID(753021712, name, description, icon).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Delete deletes the specified workspace
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2976501615, id);
}

/**
 * Dependencies returns service dependencies.
 * @returns {$CancellablePromise<string[]>}
 */
export function Dependencies() {
    return $Call.ByID(1727192465).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Duplicate duplicates an existing workspace
 * @param {string} id
 * @returns {$CancellablePromise<workspace$0.Workspace | null>}
 */
export function Duplicate(id) {
    return $Call.ByID(678095461, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportWorkspace exports a workspace as JSON bytes
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ExportWorkspace(id) {
    return $Call.ByID(145131667, id).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetActive returns the active workspace
 * @returns {$CancellablePromise<workspace$0.Workspace | null>}
 */
export function GetActive() {
    return $Call.ByID(2077193386).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAll returns all workspaces
 * @returns {$CancellablePromise<workspace$0.Workspace[]>}
 */
export function GetAll() {
    return $Call.ByID(2681812819).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ImportWorkspace imports a workspace from JSON bytes
 * @param {string} data
 * @returns {$CancellablePromise<workspace$0.Workspace | null>}
 */
export function ImportWorkspace(data) {
    return $Call.ByID(2590934202, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(3938224063);
}

/**
 * Rename renames an existing workspace
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Rename(id, name) {
    return $Call.ByID(3858122886, id, name);
}

/**
 * SaveCurrent saves the given layout for the specified workspace
 * @param {string} id
 * @param {workspace$0.PaneLayout} layout
 * @param {workspace$0.WorkspaceConnection[]} connections
 * @param {boolean} sidebarOpen
 * @param {number} sidebarWidth
 * @param {string} activeTab
 * @returns {$CancellablePromise<void>}
 */
export function SaveCurrent(id, layout, connections, sidebarOpen, sidebarWidth, activeTab) {
    return $Call.ByID(3002995454, id, layout, connections, sidebarOpen, sidebarWidth, activeTab);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2313499144);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2181627756);
}

// Private type creation functions
const $$createType0 = workspace$0.Workspace.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
