// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessEvent records who accessed what and when
 */
export class AccessEvent {
    /**
     * Creates a new AccessEvent instance.
     * @param {Partial<AccessEvent>} [$$source = {}] - The source object to create the AccessEvent.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("member_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["member_id"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * "view", "edit", "share"
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ip_address"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccessEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessEvent(/** @type {Partial<AccessEvent>} */($$parsedSource));
    }
}

/**
 * Role defines the access level for a team member
 * @readonly
 * @enum {string}
 */
export const Role = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RoleOwner: "owner",
    RoleAdmin: "admin",
    RoleMember: "member",
    RoleViewer: "viewer",
};

/**
 * TeamActivity represents a high-level team event
 */
export class TeamActivity {
    /**
     * Creates a new TeamActivity instance.
     * @param {Partial<TeamActivity>} [$$source = {}] - The source object to create the TeamActivity.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("actor_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actor_id"] = "";
        }
        if (!("actor_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actor_name"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * "member_added", "secret_added", "secret_accessed"
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["details"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamActivity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeamActivity}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamActivity(/** @type {Partial<TeamActivity>} */($$parsedSource));
    }
}

/**
 * TeamMember represents a user in the team
 */
export class TeamMember {
    /**
     * Creates a new TeamMember instance.
     * @param {Partial<TeamMember>} [$$source = {}] - The source object to create the TeamMember.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {Role}
             */
            this["role"] = Role.$zero;
        }
        if (!("joined_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["joined_at"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * For E2E encrypted sharing
             * @member
             * @type {string | undefined}
             */
            this["public_key"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamMember instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeamMember}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamMember(/** @type {Partial<TeamMember>} */($$parsedSource));
    }
}

/**
 * VaultEntry represents a shared secret or credential
 */
export class VaultEntry {
    /**
     * Creates a new VaultEntry instance.
     * @param {Partial<VaultEntry>} [$$source = {}] - The source object to create the VaultEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("entry_type" in $$source)) {
            /**
             * "password", "ssh_key", "api_token"
             * @member
             * @type {string}
             */
            this["entry_type"] = "";
        }
        if (!("encrypted_data" in $$source)) {
            /**
             * Encrypted with the team/folder key
             * @member
             * @type {string}
             */
            this["encrypted_data"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("created_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_by"] = "";
        }
        if (!("access_log" in $$source)) {
            /**
             * @member
             * @type {AccessEvent[]}
             */
            this["access_log"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultEntry}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("access_log" in $$parsedSource) {
            $$parsedSource["access_log"] = $$createField9_0($$parsedSource["access_log"]);
        }
        return new VaultEntry(/** @type {Partial<VaultEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AccessEvent.createFrom;
const $$createType2 = $Create.Array($$createType1);
