// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Block represents a single piece of evidence in the immutable chain.
 */
export class Block {
    /**
     * Creates a new Block instance.
     * @param {Partial<Block>} [$$source = {}] - The source object to create the Block.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * The actual evidence payload (e.g. JSON string of the decision)
             * @member
             * @type {string}
             */
            this["data"] = "";
        }
        if (!("data_type" in $$source)) {
            /**
             * E.g. "decision", "alert", "file_change"
             * @member
             * @type {string}
             */
            this["data_type"] = "";
        }
        if (!("previous_hash" in $$source)) {
            /**
             * The SHA-256 hash of the previous block
             * @member
             * @type {string}
             */
            this["previous_hash"] = "";
        }
        if (!("hash" in $$source)) {
            /**
             * The SHA-256 hash of this block
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Block instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Block}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new Block(/** @type {Partial<Block>} */($$parsedSource));
    }
}
