// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuditLog {
    /**
     * Creates a new AuditLog instance.
     * @param {Partial<AuditLog>} [$$source = {}] - The source object to create the AuditLog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("event_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event_type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["details"] = "";
        }
        if (!("ip_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip_address"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["merkle_hash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["merkle_index"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuditLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditLog(/** @type {Partial<AuditLog>} */($$parsedSource));
    }
}

export class Credential {
    /**
     * Creates a new Credential instance.
     * @param {Partial<Credential>} [$$source = {}] - The source object to create the Credential.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credential instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Credential}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credential(/** @type {Partial<Credential>} */($$parsedSource));
    }
}

export class EvidenceItem {
    /**
     * Creates a new EvidenceItem instance.
     * @param {Partial<EvidenceItem>} [$$source = {}] - The source object to create the EvidenceItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("incident_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["incident_id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("collector" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collector"] = "";
        }
        if (!("collected_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collected_at"] = "";
        }
        if (!("sealed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sealed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["sealed_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EvidenceItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EvidenceItem}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField12_0($$parsedSource["tags"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField13_0($$parsedSource["metadata"]);
        }
        return new EvidenceItem(/** @type {Partial<EvidenceItem>} */($$parsedSource));
    }
}

export class Host {
    /**
     * Creates a new Host instance.
     * @param {Partial<Host>} [$$source = {}] - The source object to create the Host.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_method"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["credential_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["jump_host_id"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("has_password" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_password"] = false;
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("is_favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_connected_at"] = undefined;
        }
        if (!("connection_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connection_count"] = 0;
        }
        if (!("criticality_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["criticality_score"] = 0;
        }
        if (!("criticality_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["criticality_reason"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Host}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        return new Host(/** @type {Partial<Host>} */($$parsedSource));
    }
}

export class HostEvent {
    /**
     * Creates a new HostEvent instance.
     * @param {Partial<HostEvent>} [$$source = {}] - The source object to create the HostEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("event_type" in $$source)) {
            /**
             * e.g., "failed_login"
             * @member
             * @type {string}
             */
            this["event_type"] = "";
        }
        if (!("source_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_ip"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * Enriched Geographic/DNS data
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("raw_log" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw_log"] = "";
        }
        if (!("event_hash" in $$source)) {
            /**
             * 1.3: SHA256(RawLog + Timestamp + PrevHash)
             * @member
             * @type {string}
             */
            this["event_hash"] = "";
        }
        if (!("prev_hash" in $$source)) {
            /**
             * 1.3: Reference to previous event's hash
             * @member
             * @type {string}
             */
            this["prev_hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostEvent(/** @type {Partial<HostEvent>} */($$parsedSource));
    }
}

/**
 * IdentityConnector represents an external identity provider configuration.
 */
export class IdentityConnector {
    /**
     * Creates a new IdentityConnector instance.
     * @param {Partial<IdentityConnector>} [$$source = {}] - The source object to create the IdentityConnector.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * okta, azure_ad, ldap
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("config_json" in $$source)) {
            /**
             * AES-encrypted configuration blob
             * @member
             * @type {string}
             */
            this["config_json"] = "";
        }
        if (!("sync_interval_mins" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sync_interval_mins"] = 0;
        }
        if (!("last_sync" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_sync"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("error_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_message"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdentityConnector instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IdentityConnector}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IdentityConnector(/** @type {Partial<IdentityConnector>} */($$parsedSource));
    }
}

export class Incident {
    /**
     * Creates a new Incident instance.
     * @param {Partial<Incident>} [$$source = {}] - The source object to create the Incident.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("rule_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rule_id"] = "";
        }
        if (!("group_key" in $$source)) {
            /**
             * e.g., IP address, user, host
             * @member
             * @type {string}
             */
            this["group_key"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * New, Active, Investigating, Closed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("first_seen_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["first_seen_at"] = "";
        }
        if (!("last_seen_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen_at"] = "";
        }
        if (!("event_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["event_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["owner"] = undefined;
        }
        if (!("mitre_tactics" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["mitre_tactics"] = [];
        }
        if (!("mitre_techniques" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["mitre_techniques"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resolution_reason"] = undefined;
        }
        if (!("triage_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["triage_score"] = 0;
        }
        if (!("triage_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["triage_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Incident instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Incident}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mitre_tactics" in $$parsedSource) {
            $$parsedSource["mitre_tactics"] = $$createField12_0($$parsedSource["mitre_tactics"]);
        }
        if ("mitre_techniques" in $$parsedSource) {
            $$parsedSource["mitre_techniques"] = $$createField13_0($$parsedSource["mitre_techniques"]);
        }
        return new Incident(/** @type {Partial<Incident>} */($$parsedSource));
    }
}

/**
 * Role defines a set of permissions
 */
export class Role {
    /**
     * Creates a new Role instance.
     * @param {Partial<Role>} [$$source = {}] - The source object to create the Role.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["permissions"] = [];
        }
        if (!("is_system" in $$source)) {
            /**
             * System roles cannot be deleted
             * @member
             * @type {boolean}
             */
            this["is_system"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Role instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Role}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField4_0($$parsedSource["permissions"]);
        }
        return new Role(/** @type {Partial<Role>} */($$parsedSource));
    }
}

export class RotationPolicy {
    /**
     * Creates a new RotationPolicy instance.
     * @param {Partial<RotationPolicy>} [$$source = {}] - The source object to create the RotationPolicy.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("frequency_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["frequency_days"] = 0;
        }
        if (!("last_rotation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_rotation"] = "";
        }
        if (!("next_rotation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next_rotation"] = "";
        }
        if (!("notify_only" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notify_only"] = false;
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RotationPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RotationPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RotationPolicy(/** @type {Partial<RotationPolicy>} */($$parsedSource));
    }
}

/**
 * SIEMStore defines the interface for security event monitoring and analytics.
 * @typedef {any} SIEMStore
 */

export class SavedSearch {
    /**
     * Creates a new SavedSearch instance.
     * @param {Partial<SavedSearch>} [$$source = {}] - The source object to create the SavedSearch.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedSearch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedSearch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedSearch(/** @type {Partial<SavedSearch>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ended_at"] = undefined;
        }
        if (!("duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_seconds"] = 0;
        }
        if (!("bytes_sent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_sent"] = 0;
        }
        if (!("bytes_received" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_received"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["recording_path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["variables"] = [];
        }
        if (!("use_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["use_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField6_0($$parsedSource["variables"]);
        }
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

/**
 * SuppressionRule defines criteria for silencing alerts to reduce false positives.
 */
export class SuppressionRule {
    /**
     * Creates a new SuppressionRule instance.
     * @param {Partial<SuppressionRule>} [$$source = {}] - The source object to create the SuppressionRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("rule_id" in $$source)) {
            /**
             * The ID of the detection rule to suppress (empty for global)
             * @member
             * @type {string}
             */
            this["rule_id"] = "";
        }
        if (!("field" in $$source)) {
            /**
             * e.g. "host_id", "user_name", "src_ip"
             * @member
             * @type {string}
             */
            this["field"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * The value to match
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("is_regex" in $$source)) {
            /**
             * Whether Value is a regex pattern
             * @member
             * @type {boolean}
             */
            this["is_regex"] = false;
        }
        if (!("expires_at" in $$source)) {
            /**
             * RFC3339 timestamp (empty for permanent)
             * @member
             * @type {string}
             */
            this["expires_at"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }
        if (!("last_matched_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_matched_at"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuppressionRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SuppressionRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SuppressionRule(/** @type {Partial<SuppressionRule>} */($$parsedSource));
    }
}

/**
 * User represents an identity within a tenant
 */
export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tenant_id"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("auth_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_provider"] = "";
        }
        if (!("is_mfa_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_mfa_enabled"] = false;
        }
        if (!("role_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role_id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("last_login_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_login_at"] = "";
        }
        if (!("criticality_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["criticality_score"] = 0;
        }
        if (!("criticality_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["criticality_reason"] = "";
        }
        if (!("external_id" in $$source)) {
            /**
             * SCIM Normalization fields
             * @member
             * @type {string}
             */
            this["external_id"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("user_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("department" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["department"] = "";
        }
        if (!("organization" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["organization"] = "";
        }
        if (!("preferred_language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preferred_language"] = "";
        }
        if (!("groups_json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groups_json"] = "";
        }
        if (!("scim_attributes_json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scim_attributes_json"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
