// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Manifest describes a plugin's metadata and requirements
 */
export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Identity
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("license" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["license"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["homepage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repository"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * Type and capabilities
             * @member
             * @type {PluginType}
             */
            this["type"] = PluginType.$zero;
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {Permission[]}
             */
            this["permissions"] = [];
        }
        if (!("main" in $$source)) {
            /**
             * Entry points
             * WASM file path
             * @member
             * @type {string}
             */
            this["main"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Frontend script
             * @member
             * @type {string | undefined}
             */
            this["ui_entry"] = undefined;
        }
        if (!("max_memory_mb" in $$source)) {
            /**
             * Resources
             * @member
             * @type {number}
             */
            this["max_memory_mb"] = 0;
        }
        if (!("max_cpu_pct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_cpu_pct"] = 0;
        }
        if (!("timeout_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout_sec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Hooks
             * @member
             * @type {PluginHooks | undefined}
             */
            this["hooks"] = undefined;
        }
        if (!("min_app_version" in $$source)) {
            /**
             * Dependencies
             * @member
             * @type {string}
             */
            this["min_app_version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dependencies"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField17_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField9_0($$parsedSource["permissions"]);
        }
        if ("hooks" in $$parsedSource) {
            $$parsedSource["hooks"] = $$createField15_0($$parsedSource["hooks"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField17_0($$parsedSource["dependencies"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

/**
 * Permission defines what a plugin can access
 * @readonly
 * @enum {string}
 */
export const Permission = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PermSSHRead: "ssh.read",
    PermSSHWrite: "ssh.write",
    PermSSHConnect: "ssh.connect",
    PermVaultRead: "vault.read",
    PermFilesystem: "filesystem",
    PermNetwork: "network",
    PermUIRender: "ui.render",
    PermEvents: "events",
    PermNotifications: "notifications",
};

export class Plugin {
    /**
     * Creates a new Plugin instance.
     * @param {Partial<Plugin>} [$$source = {}] - The source object to create the Plugin.
     */
    constructor($$source = {}) {
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {Manifest | null}
             */
            this["manifest"] = null;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {PluginState}
             */
            this["state"] = PluginState.$zero;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plugin}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        return new Plugin(/** @type {Partial<Plugin>} */($$parsedSource));
    }
}

export class PluginHooks {
    /**
     * Creates a new PluginHooks instance.
     * @param {Partial<PluginHooks>} [$$source = {}] - The source object to create the PluginHooks.
     */
    constructor($$source = {}) {
        if (!("on_connect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_connect"] = false;
        }
        if (!("on_disconnect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_disconnect"] = false;
        }
        if (!("on_command" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_command"] = false;
        }
        if (!("on_output" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_output"] = false;
        }
        if (!("on_startup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_startup"] = false;
        }
        if (!("on_shutdown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_shutdown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginHooks instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginHooks}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginHooks(/** @type {Partial<PluginHooks>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PluginState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateInstalled: "installed",
    StateActive: "active",
    StateDisabled: "disabled",
    StateError: "error",
};

/**
 * PluginType defines the kind of plugin
 * @readonly
 * @enum {string}
 */
export const PluginType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PluginTypeTerminal: "terminal",
    PluginTypeAutomation: "automation",
    PluginTypeUI: "ui",
    PluginTypeSecurity: "security",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PluginHooks.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Manifest.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
