// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntityProfile represents the behavioral baseline for a user or host.
 */
export class EntityProfile {
    /**
     * Creates a new EntityProfile instance.
     * @param {Partial<EntityProfile>} [$$source = {}] - The source object to create the EntityProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "user" or "host"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen"] = "";
        }
        if (!("risk_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["risk_score"] = 0;
        }
        if (!("features" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["features"] = {};
        }
        if (!("observations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["observations"] = 0;
        }
        if (!("peer_group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peer_group_id"] = "";
        }
        if (!("risk_history" in $$source)) {
            /**
             * @member
             * @type {RiskPoint[]}
             */
            this["risk_history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntityProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntityProfile}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField4_0($$parsedSource["features"]);
        }
        if ("risk_history" in $$parsedSource) {
            $$parsedSource["risk_history"] = $$createField7_0($$parsedSource["risk_history"]);
        }
        return new EntityProfile(/** @type {Partial<EntityProfile>} */($$parsedSource));
    }
}

export class RiskPoint {
    /**
     * Creates a new RiskPoint instance.
     * @param {Partial<RiskPoint>} [$$source = {}] - The source object to create the RiskPoint.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RiskPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RiskPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RiskPoint(/** @type {Partial<RiskPoint>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = RiskPoint.createFrom;
const $$createType2 = $Create.Array($$createType1);
