// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LoadStatus represents the operational health of the pipeline.
 * @readonly
 * @enum {number}
 */
export const LoadStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * Normal operation
     */
    LoadHealthy: 0,

    /**
     * High EPS or near-full buffers
     */
    LoadDegraded: 1,

    /**
     * Extreme EPS or critically full buffers
     */
    LoadCritical: 2,
};
