// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ApprovalRequest represents a destructive action held in staging until authorized
 */
export class ApprovalRequest {
    /**
     * Creates a new ApprovalRequest instance.
     * @param {Partial<ApprovalRequest>} [$$source = {}] - The source object to create the ApprovalRequest.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("RequesterID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RequesterID"] = "";
        }
        if (!("ActionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ActionType"] = "";
        }
        if (!("TargetResource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TargetResource"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {ApprovalStatus}
             */
            this["Status"] = ApprovalStatus.$zero;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }
        if (!("ApprovedBy" in $$source)) {
            /**
             * first approver (legacy compat)
             * @member
             * @type {string}
             */
            this["ApprovedBy"] = "";
        }
        if (!("ApprovedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ApprovedAt"] = "";
        }
        if (!("RequiredApprovals" in $$source)) {
            /**
             * Quorum fields for Two-Man Rule
             * @member
             * @type {number}
             */
            this["RequiredApprovals"] = 0;
        }
        if (!("GrantedBy" in $$source)) {
            /**
             * all approver IDs in order
             * @member
             * @type {string[]}
             */
            this["GrantedBy"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalRequest}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("GrantedBy" in $$parsedSource) {
            $$parsedSource["GrantedBy"] = $$createField9_0($$parsedSource["GrantedBy"]);
        }
        return new ApprovalRequest(/** @type {Partial<ApprovalRequest>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ApprovalStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusApproved: "approved",
    StatusDenied: "denied",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
