// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * DiagnosticsSnapshot captures a point-in-time view of all critical platform
 * subsystems. This is the payload served to the frontend Diagnostics Modal,
 * giving analysts real-time confidence in data freshness during incidents.
 */
export class DiagnosticsSnapshot {
    /**
     * Creates a new DiagnosticsSnapshot instance.
     * @param {Partial<DiagnosticsSnapshot>} [$$source = {}] - The source object to create the DiagnosticsSnapshot.
     */
    constructor($$source = {}) {
        if (!("captured_at" in $$source)) {
            /**
             * Time this snapshot was captured
             * @member
             * @type {string}
             */
            this["captured_at"] = "";
        }
        if (!("event_bus" in $$source)) {
            /**
             * Event Bus health
             * @member
             * @type {EventBusDiag}
             */
            this["event_bus"] = (new EventBusDiag());
        }
        if (!("ingest" in $$source)) {
            /**
             * Ingest pipeline metrics (populated externally via SetIngestMetrics)
             * @member
             * @type {IngestDiag}
             */
            this["ingest"] = (new IngestDiag());
        }
        if (!("runtime" in $$source)) {
            /**
             * Go runtime vitals
             * @member
             * @type {RuntimeDiag}
             */
            this["runtime"] = (new RuntimeDiag());
        }
        if (!("query" in $$source)) {
            /**
             * Query subsystem latency (populated via RecordQueryLatency)
             * @member
             * @type {QueryDiag}
             */
            this["query"] = (new QueryDiag());
        }
        if (!("health_grade" in $$source)) {
            /**
             * Overall platform health grade: A / B / C / DEGRADED
             * @member
             * @type {string}
             */
            this["health_grade"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event_bus" in $$parsedSource) {
            $$parsedSource["event_bus"] = $$createField1_0($$parsedSource["event_bus"]);
        }
        if ("ingest" in $$parsedSource) {
            $$parsedSource["ingest"] = $$createField2_0($$parsedSource["ingest"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField3_0($$parsedSource["runtime"]);
        }
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField4_0($$parsedSource["query"]);
        }
        return new DiagnosticsSnapshot(/** @type {Partial<DiagnosticsSnapshot>} */($$parsedSource));
    }
}

/**
 * EventBusDiag describes the health of the internal event bus.
 */
export class EventBusDiag {
    /**
     * Creates a new EventBusDiag instance.
     * @param {Partial<EventBusDiag>} [$$source = {}] - The source object to create the EventBusDiag.
     */
    constructor($$source = {}) {
        if (!("dropped_events" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dropped_events"] = 0;
        }
        if (!("rate_limit_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rate_limit_active"] = false;
        }
        if (!("lag_estimate_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lag_estimate_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventBusDiag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventBusDiag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventBusDiag(/** @type {Partial<EventBusDiag>} */($$parsedSource));
    }
}

/**
 * HostTelemetry represents system resources for a remote host
 */
export class HostTelemetry {
    /**
     * Creates a new HostTelemetry instance.
     * @param {Partial<HostTelemetry>} [$$source = {}] - The source object to create the HostTelemetry.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("cpu_usage" in $$source)) {
            /**
             * Percentage 0-100
             * @member
             * @type {number}
             */
            this["cpu_usage"] = 0;
        }
        if (!("mem_used_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem_used_mb"] = 0;
        }
        if (!("mem_total_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mem_total_mb"] = 0;
        }
        if (!("disk_used_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["disk_used_gb"] = 0;
        }
        if (!("disk_total_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["disk_total_gb"] = 0;
        }
        if (!("load_avg" in $$source)) {
            /**
             * 1-minute load average
             * @member
             * @type {number}
             */
            this["load_avg"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostTelemetry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostTelemetry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostTelemetry(/** @type {Partial<HostTelemetry>} */($$parsedSource));
    }
}

/**
 * IngestDiag mirrors the pipeline metrics relevant to analysts.
 */
export class IngestDiag {
    /**
     * Creates a new IngestDiag instance.
     * @param {Partial<IngestDiag>} [$$source = {}] - The source object to create the IngestDiag.
     */
    constructor($$source = {}) {
        if (!("current_eps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current_eps"] = 0;
        }
        if (!("target_eps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target_eps"] = 0;
        }
        if (!("percent_of_target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent_of_target"] = 0;
        }
        if (!("buffer_fill_pct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buffer_fill_pct"] = 0;
        }
        if (!("dropped_total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dropped_total"] = 0;
        }
        if (!("worker_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["worker_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestDiag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IngestDiag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestDiag(/** @type {Partial<IngestDiag>} */($$parsedSource));
    }
}

/**
 * Metric represents a single metric reading
 */
export class Metric {
    /**
     * Creates a new Metric instance.
     * @param {Partial<Metric>} [$$source = {}] - The source object to create the Metric.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {MetricType}
             */
            this["type"] = MetricType.$zero;
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["labels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metric instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Metric}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField3_0($$parsedSource["labels"]);
        }
        return new Metric(/** @type {Partial<Metric>} */($$parsedSource));
    }
}

/**
 * MetricType defines the kind of metric
 * @readonly
 * @enum {string}
 */
export const MetricType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricCounter: "counter",
    MetricGauge: "gauge",
    MetricHistogram: "histogram",
};

/**
 * ProbeResult captures the outcome of an execution
 */
export class ProbeResult {
    /**
     * Creates a new ProbeResult instance.
     * @param {Partial<ProbeResult>} [$$source = {}] - The source object to create the ProbeResult.
     */
    constructor($$source = {}) {
        if (!("probe_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["probe_id"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ProbeStatus}
             */
            this["status"] = ProbeStatus.$zero;
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["latency"] = time$0.Duration.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult(/** @type {Partial<ProbeResult>} */($$parsedSource));
    }
}

/**
 * ProbeStatus defines the outcome of a check
 * @readonly
 * @enum {string}
 */
export const ProbeStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusUp: "up",
    StatusDown: "down",
};

/**
 * QueryDiag reports DuckDB/SQLite query performance so analysts know if
 * dashboards are showing stale data.
 */
export class QueryDiag {
    /**
     * Creates a new QueryDiag instance.
     * @param {Partial<QueryDiag>} [$$source = {}] - The source object to create the QueryDiag.
     */
    constructor($$source = {}) {
        if (!("last_query_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_query_ms"] = 0;
        }
        if (!("avg_query_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_query_ms"] = 0;
        }
        if (!("p99_query_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p99_query_ms"] = 0;
        }
        if (!("slow_query_count" in $$source)) {
            /**
             * queries > 500ms
             * @member
             * @type {number}
             */
            this["slow_query_count"] = 0;
        }
        if (!("total_queries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_queries"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryDiag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryDiag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryDiag(/** @type {Partial<QueryDiag>} */($$parsedSource));
    }
}

/**
 * RuntimeDiag captures Go runtime internals useful for memory pressure detection.
 */
export class RuntimeDiag {
    /**
     * Creates a new RuntimeDiag instance.
     * @param {Partial<RuntimeDiag>} [$$source = {}] - The source object to create the RuntimeDiag.
     */
    constructor($$source = {}) {
        if (!("goroutines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["goroutines"] = 0;
        }
        if (!("heap_alloc_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heap_alloc_mb"] = 0;
        }
        if (!("heap_sys_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heap_sys_mb"] = 0;
        }
        if (!("gc_pause_ns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gc_pause_ns"] = 0;
        }
        if (!("gc_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gc_count"] = 0;
        }
        if (!("num_cpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["num_cpu"] = 0;
        }
        if (!("go_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["go_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeDiag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeDiag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeDiag(/** @type {Partial<RuntimeDiag>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EventBusDiag.createFrom;
const $$createType1 = IngestDiag.createFrom;
const $$createType2 = RuntimeDiag.createFrom;
const $$createType3 = QueryDiag.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
