// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NotificationConfig holds all provider credentials (stored in Vault)
 */
export class NotificationConfig {
    /**
     * Creates a new NotificationConfig instance.
     * @param {Partial<NotificationConfig>} [$$source = {}] - The source object to create the NotificationConfig.
     */
    constructor($$source = {}) {
        if (!("smtp_host" in $$source)) {
            /**
             * Email (SMTP)
             * @member
             * @type {string}
             */
            this["smtp_host"] = "";
        }
        if (!("smtp_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["smtp_port"] = 0;
        }
        if (!("smtp_username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtp_username"] = "";
        }
        if (!("smtp_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtp_password"] = "";
        }
        if (!("to_email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to_email"] = "";
        }
        if (!("telegram_token" in $$source)) {
            /**
             * Telegram
             * @member
             * @type {string}
             */
            this["telegram_token"] = "";
        }
        if (!("telegram_chat_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["telegram_chat_id"] = "";
        }
        if (!("twilio_sid" in $$source)) {
            /**
             * Twilio (SMS + WhatsApp)
             * @member
             * @type {string}
             */
            this["twilio_sid"] = "";
        }
        if (!("twilio_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["twilio_token"] = "";
        }
        if (!("twilio_from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["twilio_from"] = "";
        }
        if (!("to_phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to_phone"] = "";
        }
        if (!("enable_email" in $$source)) {
            /**
             * Per-channel toggles
             * @member
             * @type {boolean}
             */
            this["enable_email"] = false;
        }
        if (!("enable_telegram" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable_telegram"] = false;
        }
        if (!("enable_sms" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable_sms"] = false;
        }
        if (!("enable_whatsapp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable_whatsapp"] = false;
        }
        if (!("enable_webhook" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable_webhook"] = false;
        }
        if (!("webhook_url" in $$source)) {
            /**
             * Webhook
             * @member
             * @type {string}
             */
            this["webhook_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["webhook_headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HMAC-SHA256 signing
             * @member
             * @type {string | undefined}
             */
            this["webhook_secret"] = undefined;
        }
        if (!("enable_jira" in $$source)) {
            /**
             * Jira
             * @member
             * @type {boolean}
             */
            this["enable_jira"] = false;
        }
        if (!("jira_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jira_url"] = "";
        }
        if (!("jira_user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jira_user"] = "";
        }
        if (!("jira_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jira_token"] = "";
        }
        if (!("jira_project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jira_project"] = "";
        }
        if (!("jira_issue_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jira_issue_type"] = "";
        }
        if (!("enable_servicenow" in $$source)) {
            /**
             * ServiceNow
             * @member
             * @type {boolean}
             */
            this["enable_servicenow"] = false;
        }
        if (!("servicenow_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["servicenow_url"] = "";
        }
        if (!("servicenow_user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["servicenow_user"] = "";
        }
        if (!("servicenow_pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["servicenow_pass"] = "";
        }
        if (!("servicenow_table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["servicenow_table"] = "";
        }
        if (!("enable_slack" in $$source)) {
            /**
             * Slack (first-class)
             * @member
             * @type {boolean}
             */
            this["enable_slack"] = false;
        }
        if (!("slack_webhook_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slack_webhook_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["slack_channel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["slack_bot_token"] = undefined;
        }
        if (!("enable_teams" in $$source)) {
            /**
             * Microsoft Teams (first-class)
             * @member
             * @type {boolean}
             */
            this["enable_teams"] = false;
        }
        if (!("teams_webhook_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teams_webhook_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotificationConfig}
     */
    static createFrom($$source = {}) {
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhook_headers" in $$parsedSource) {
            $$parsedSource["webhook_headers"] = $$createField17_0($$parsedSource["webhook_headers"]);
        }
        return new NotificationConfig(/** @type {Partial<NotificationConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
