// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PaneLayout defines how terminal panes are arranged
 */
export class PaneLayout {
    /**
     * Creates a new PaneLayout instance.
     * @param {Partial<PaneLayout>} [$$source = {}] - The source object to create the PaneLayout.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "terminal", "split-h", "split-v"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host_label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PaneLayout[] | undefined}
             */
            this["children"] = undefined;
        }
        if (!("size" in $$source)) {
            /**
             * 0.0 - 1.0, relative size
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaneLayout instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaneLayout}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new PaneLayout(/** @type {Partial<PaneLayout>} */($$parsedSource));
    }
}

/**
 * Workspace represents a saveable session layout
 */
export class Workspace {
    /**
     * Creates a new Workspace instance.
     * @param {Partial<Workspace>} [$$source = {}] - The source object to create the Workspace.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("layout" in $$source)) {
            /**
             * @member
             * @type {PaneLayout}
             */
            this["layout"] = (new PaneLayout());
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {WorkspaceConnection[]}
             */
            this["connections"] = [];
        }
        if (!("sidebar_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sidebar_open"] = false;
        }
        if (!("sidebar_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sidebar_width"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["active_tab"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["theme"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("is_default" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_default"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workspace}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        const $$createField13_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField3_0($$parsedSource["layout"]);
        }
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField4_0($$parsedSource["connections"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField13_0($$parsedSource["tags"]);
        }
        return new Workspace(/** @type {Partial<Workspace>} */($$parsedSource));
    }
}

/**
 * WorkspaceConnection defines a connection within a workspace
 */
export class WorkspaceConnection {
    /**
     * Creates a new WorkspaceConnection instance.
     * @param {Partial<WorkspaceConnection>} [$$source = {}] - The source object to create the WorkspaceConnection.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("pane_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pane_id"] = "";
        }
        if (!("auto_connect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_connect"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["init_commands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["environment"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceConnection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceConnection}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("init_commands" in $$parsedSource) {
            $$parsedSource["init_commands"] = $$createField3_0($$parsedSource["init_commands"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField4_0($$parsedSource["environment"]);
        }
        return new WorkspaceConnection(/** @type {Partial<WorkspaceConnection>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PaneLayout.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = WorkspaceConnection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
