package analytics

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"time"

	"github.com/kingknull/oblivrashell/internal/database"
	"github.com/kingknull/oblivrashell/internal/oql"
	"github.com/kingknull/oblivrashell/internal/platform"
	"github.com/kingknull/oblivrashell/internal/storage"
)

// ReportFactory handles the generation of reports from templates.
type ReportFactory struct {
	executor *oql.Executor
	repo     database.ReportStore
	hotStore *storage.HotStore
}

func NewReportFactory(repo database.ReportStore, executor *oql.Executor, hotStore *storage.HotStore) *ReportFactory {
	return &ReportFactory{
		repo:     repo,
		executor: executor,
		hotStore: hotStore,
	}
}

// SectionResult holds the data for a single report section.
type SectionResult struct {
	Title string
	Type  string
	Data  *oql.QueryResult
}

// GenerateHTML renders a report to an HTML file and returns the path.
func (f *ReportFactory) GenerateHTML(ctx context.Context, templateID string, start, end string) (string, error) {
	tmpl, err := f.repo.GetTemplate(ctx, templateID)
	if err != nil {
		return "", err
	}

	var sections []database.GenericReportSection
	if err := json.Unmarshal([]byte(tmpl.SectionsJSON), &sections); err != nil {
		return "", fmt.Errorf("malformed template sections: %w", err)
	}

	var results []SectionResult
	for _, sec := range sections {
		// RunOQL should be accessible here
		res, err := f.runQuery(ctx, sec.Query)
		if err != nil {
			continue
		}
		results = append(results, SectionResult{
			Title: sec.Title,
			Type:  sec.Type,
			Data:  res,
		})
	}

	htmlData, err := f.renderTemplate(tmpl.Name, start, end, results)
	if err != nil {
		return "", err
	}

	reportsDir := filepath.Join(platform.DataDir(), "reports", tmpl.TenantID)
	os.MkdirAll(reportsDir, 0700)
	
	filename := fmt.Sprintf("%s_%s.html", templateID, time.Now().Format("20060102_150405"))
	filePath := filepath.Join(reportsDir, filename)
	
	if err := os.WriteFile(filePath, htmlData, 0600); err != nil {
		return "", err
	}

	return filePath, nil
}

func (f *ReportFactory) runQuery(ctx context.Context, query string) (*oql.QueryResult, error) {
	if f.executor == nil || f.hotStore == nil {
		return nil, fmt.Errorf("executor or hotstore not initialized")
	}

	tenantID := "default_tenant"
	if id, ok := ctx.Value("tenant_id").(string); ok {
		tenantID = id
	}

	source := oql.NewBadgerSource(f.hotStore, tenantID)
	f.executor.SetSource(source)

	return f.executor.Execute(ctx, query, nil, nil)
}

func (f *ReportFactory) renderTemplate(title, start, end string, results []SectionResult) ([]byte, error) {
	const reportHTML = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ .Title }} - OBLIVRA Report</title>
    <style>
        body { font-family: sans-serif; background: #0f1117; color: #e4e6f0; padding: 40px; }
        .header { border-bottom: 2px solid #6366f1; margin-bottom: 30px; padding-bottom: 20px; }
        .section { background: #1a1d27; border-radius: 8px; padding: 20px; margin-bottom: 20px; border: 1px solid #2a2d3a; }
        h1 { color: #6366f1; }
        h2 { border-left: 4px solid #6366f1; padding-left: 10px; font-size: 1.2rem; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { text-align: left; padding: 10px; border-bottom: 1px solid #2a2d3a; }
        th { background: #2a2d3a; font-size: 0.8rem; text-transform: uppercase; color: #8b8fa3; }
        .meta { color: #8b8fa3; font-size: 0.9rem; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ .Title }}</h1>
        <div class="meta">OBLIVRA Master Report Factory • Period: {{ .Start }} to {{ .End }}</div>
    </div>

    {{ range .Results }}
    <div class="section">
        <h2>{{ .Title }}</h2>
        {{ if eq .Type "table" }}
            <table>
                <thead>
                    <tr>
                        {{ range .Data.Columns }}
                        <th>{{ .Name }}</th>
                        {{ end }}
                    </tr>
                </thead>
                <tbody>
                    {{ range .Data.Rows }}
                    <tr>
                        {{ $row := . }}
                        {{ range $.Data.Columns }}
                        <td>{{ index $row .Name }}</td>
                        {{ end }}
                    </tr>
                    {{ end }}
                </tbody>
            </table>
        {{ else if eq .Type "summary" }}
            {{ range .Data.Rows }}
               <div style="font-size: 1.2rem; font-weight: bold; margin-top: 10px;">{{ index . "count" }} Total Events</div>
            {{ end }}
        {{ end }}
    </div>
    {{ end }}

    <div style="text-align: center; margin-top: 40px; color: #8b8fa3; font-size: 0.8rem;">
        Generated by OBLIVRA Security Platform • {{ now }}
    </div>
</body>
</html>`

	tmpl, err := template.New("factory-report").Funcs(template.FuncMap{
		"now": func() string { return time.Now().Format(time.RFC3339) },
	}).Parse(reportHTML)
	if err != nil {
		return nil, err
	}

	data := struct {
		Title   string
		Start   string
		End     string
		Results []SectionResult
	}{
		Title:   title,
		Start:   start,
		End:     end,
		Results: results,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
