// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Campaign represents an active multi-stage attack sequence linked to an entity.
 */
export class Campaign {
    /**
     * Creates a new Campaign instance.
     * @param {Partial<Campaign>} [$$source = {}] - The source object to create the Campaign.
     */
    constructor($$source = {}) {
        if (!("entity_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entity_id"] = "";
        }
        if (!("tactics" in $$source)) {
            /**
             * TacticID -> true
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["tactics"] = {};
        }
        if (!("alerts" in $$source)) {
            /**
             * @member
             * @type {FusionAlertInfo[]}
             */
            this["alerts"] = [];
        }
        if (!("probability" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["probability"] = 0;
        }
        if (!("first_seen" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["first_seen"] = null;
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["last_seen"] = null;
        }
        if (!("is_triggered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_triggered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Campaign instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Campaign}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tactics" in $$parsedSource) {
            $$parsedSource["tactics"] = $$createField1_0($$parsedSource["tactics"]);
        }
        if ("alerts" in $$parsedSource) {
            $$parsedSource["alerts"] = $$createField2_0($$parsedSource["alerts"]);
        }
        return new Campaign(/** @type {Partial<Campaign>} */($$parsedSource));
    }
}

/**
 * CampaignTimeline is the reconstructed story of an attack campaign.
 */
export class CampaignTimeline {
    /**
     * Creates a new CampaignTimeline instance.
     * @param {Partial<CampaignTimeline>} [$$source = {}] - The source object to create the CampaignTimeline.
     */
    constructor($$source = {}) {
        if (!("campaign_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["campaign_id"] = "";
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {TimelineEvent[]}
             */
            this["events"] = [];
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start"] = null;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["end"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CampaignTimeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CampaignTimeline}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField1_0($$parsedSource["events"]);
        }
        return new CampaignTimeline(/** @type {Partial<CampaignTimeline>} */($$parsedSource));
    }
}

/**
 * CounterfactualResult captures the delta between original and simulated detection outcomes.
 */
export class CounterfactualResult {
    /**
     * Creates a new CounterfactualResult instance.
     * @param {Partial<CounterfactualResult>} [$$source = {}] - The source object to create the CounterfactualResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("event_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["event_count"] = 0;
        }
        if (!("disabled_rules" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["disabled_rules"] = [];
        }
        if (!("original_matches" in $$source)) {
            /**
             * @member
             * @type {Match[]}
             */
            this["original_matches"] = [];
        }
        if (!("simulated_matches" in $$source)) {
            /**
             * @member
             * @type {Match[]}
             */
            this["simulated_matches"] = [];
        }
        if (!("missed_detections" in $$source)) {
            /**
             * @member
             * @type {Match[]}
             */
            this["missed_detections"] = [];
        }
        if (!("false_positives_removed" in $$source)) {
            /**
             * @member
             * @type {Match[]}
             */
            this["false_positives_removed"] = [];
        }
        if (!("impact_summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["impact_summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CounterfactualResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CounterfactualResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("disabled_rules" in $$parsedSource) {
            $$parsedSource["disabled_rules"] = $$createField3_0($$parsedSource["disabled_rules"]);
        }
        if ("original_matches" in $$parsedSource) {
            $$parsedSource["original_matches"] = $$createField4_0($$parsedSource["original_matches"]);
        }
        if ("simulated_matches" in $$parsedSource) {
            $$parsedSource["simulated_matches"] = $$createField5_0($$parsedSource["simulated_matches"]);
        }
        if ("missed_detections" in $$parsedSource) {
            $$parsedSource["missed_detections"] = $$createField6_0($$parsedSource["missed_detections"]);
        }
        if ("false_positives_removed" in $$parsedSource) {
            $$parsedSource["false_positives_removed"] = $$createField7_0($$parsedSource["false_positives_removed"]);
        }
        return new CounterfactualResult(/** @type {Partial<CounterfactualResult>} */($$parsedSource));
    }
}

/**
 * Evaluator wraps RuleEngine with state tracking for thresholds/sequences.
 */
export class Evaluator {
    /**
     * Creates a new Evaluator instance.
     * @param {Partial<Evaluator>} [$$source = {}] - The source object to create the Evaluator.
     */
    constructor($$source = {}) {
        if (!("IsLocal" in $$source)) {
            /**
             * Sharding scope
             * @member
             * @type {boolean}
             */
            this["IsLocal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Evaluator instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Evaluator}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Evaluator(/** @type {Partial<Evaluator>} */($$parsedSource));
    }
}

/**
 * Event represents a normalized log event for the detection engine to process
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("TenantID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TenantID"] = "";
        }
        if (!("EventType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EventType"] = "";
        }
        if (!("SourceIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SourceIP"] = "";
        }
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("HostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["HostID"] = "";
        }
        if (!("RawLog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RawLog"] = "";
        }
        if (!("Location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Location"] = "";
        }
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

export class FusionAlertInfo {
    /**
     * Creates a new FusionAlertInfo instance.
     * @param {Partial<FusionAlertInfo>} [$$source = {}] - The source object to create the FusionAlertInfo.
     */
    constructor($$source = {}) {
        if (!("rule_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rule_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("tactic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tactic"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FusionAlertInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FusionAlertInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FusionAlertInfo(/** @type {Partial<FusionAlertInfo>} */($$parsedSource));
    }
}

/**
 * Match represents a triggered detection rule.
 */
export class Match {
    /**
     * Creates a new Match instance.
     * @param {Partial<Match>} [$$source = {}] - The source object to create the Match.
     */
    constructor($$source = {}) {
        if (!("TenantID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TenantID"] = "";
        }
        if (!("RuleID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RuleID"] = "";
        }
        if (!("RuleName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RuleName"] = "";
        }
        if (!("Severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Severity"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("MitreTactics" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["MitreTactics"] = [];
        }
        if (!("MitreTechniques" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["MitreTechniques"] = [];
        }
        if (!("TriggeredAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TriggeredAt"] = "";
        }
        if (!("Events" in $$source)) {
            /**
             * @member
             * @type {Event[]}
             */
            this["Events"] = [];
        }
        if (!("Context" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["Context"] = {};
        }
        if (!("confidence_score" in $$source)) {
            /**
             * ConfidenceScore is 0–100. It reflects how strongly the rule evidence
             * supports the alert — higher threshold saturation and severity raises it.
             * @member
             * @type {number}
             */
            this["confidence_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Match}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("MitreTactics" in $$parsedSource) {
            $$parsedSource["MitreTactics"] = $$createField5_0($$parsedSource["MitreTactics"]);
        }
        if ("MitreTechniques" in $$parsedSource) {
            $$parsedSource["MitreTechniques"] = $$createField6_0($$parsedSource["MitreTechniques"]);
        }
        if ("Events" in $$parsedSource) {
            $$parsedSource["Events"] = $$createField8_0($$parsedSource["Events"]);
        }
        if ("Context" in $$parsedSource) {
            $$parsedSource["Context"] = $$createField9_0($$parsedSource["Context"]);
        }
        return new Match(/** @type {Partial<Match>} */($$parsedSource));
    }
}

/**
 * Rule represents a parsed detection rule from YAML.
 */
export class Rule {
    /**
     * Creates a new Rule instance.
     * @param {Partial<Rule>} [$$source = {}] - The source object to create the Rule.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Severity" in $$source)) {
            /**
             * low, medium, high, critical
             * @member
             * @type {string}
             */
            this["Severity"] = "";
        }
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {RuleType}
             */
            this["Type"] = RuleType.$zero;
        }
        if (!("Version" in $$source)) {
            /**
             * 22.4: Semantic version (semver) for rule versioning and rollback.
             * Format: "1.0.0" — incremented on every rule change.
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Conditions" in $$source)) {
            /**
             * e.g. {"EventType": "failed_login", "User": "root"}
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["Conditions"] = {};
        }
        if (!("MitreTactics" in $$source)) {
            /**
             * MITRE Framework
             * e.g. ["Initial Access", "Credential Access"]
             * @member
             * @type {string[]}
             */
            this["MitreTactics"] = [];
        }
        if (!("MitreTechniques" in $$source)) {
            /**
             * e.g. ["T1078", "T1110"]
             * @member
             * @type {string[]}
             */
            this["MitreTechniques"] = [];
        }
        if (!("Threshold" in $$source)) {
            /**
             * Threshold/Frequency Specifics
             * Number of occurrences
             * @member
             * @type {number}
             */
            this["Threshold"] = 0;
        }
        if (!("WindowSec" in $$source)) {
            /**
             * Evaluation window in seconds
             * @member
             * @type {number}
             */
            this["WindowSec"] = 0;
        }
        if (!("Sequence" in $$source)) {
            /**
             * Sequence Specifics
             * Define explicit causal chains
             * @member
             * @type {RuleSequenceStep[]}
             */
            this["Sequence"] = [];
        }
        if (!("GroupBy" in $$source)) {
            /**
             * Grouping (e.g. group by source_ip to track per-ip frequency)
             * @member
             * @type {string[]}
             */
            this["GroupBy"] = [];
        }
        if (!("DedupWindowSec" in $$source)) {
            /**
             * Deduplication
             * Prevent alert spam
             * @member
             * @type {number}
             */
            this["DedupWindowSec"] = 0;
        }
        if (!("IsGlobal" in $$source)) {
            /**
             * 22.5: Sharding Hint. If true, rule is evaluated in the CorrelationHub, not in local shards.
             * @member
             * @type {boolean}
             */
            this["IsGlobal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rule}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType5;
        const $$createField11_0 = $$createType13;
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Conditions" in $$parsedSource) {
            $$parsedSource["Conditions"] = $$createField6_0($$parsedSource["Conditions"]);
        }
        if ("MitreTactics" in $$parsedSource) {
            $$parsedSource["MitreTactics"] = $$createField7_0($$parsedSource["MitreTactics"]);
        }
        if ("MitreTechniques" in $$parsedSource) {
            $$parsedSource["MitreTechniques"] = $$createField8_0($$parsedSource["MitreTechniques"]);
        }
        if ("Sequence" in $$parsedSource) {
            $$parsedSource["Sequence"] = $$createField11_0($$parsedSource["Sequence"]);
        }
        if ("GroupBy" in $$parsedSource) {
            $$parsedSource["GroupBy"] = $$createField12_0($$parsedSource["GroupBy"]);
        }
        return new Rule(/** @type {Partial<Rule>} */($$parsedSource));
    }
}

/**
 * RuleSequenceStep represents a required stage in a SequenceRule.
 */
export class RuleSequenceStep {
    /**
     * Creates a new RuleSequenceStep instance.
     * @param {Partial<RuleSequenceStep>} [$$source = {}] - The source object to create the RuleSequenceStep.
     */
    constructor($$source = {}) {
        if (!("StepID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StepID"] = "";
        }
        if (!("Conditions" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["Conditions"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleSequenceStep instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuleSequenceStep}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Conditions" in $$parsedSource) {
            $$parsedSource["Conditions"] = $$createField1_0($$parsedSource["Conditions"]);
        }
        return new RuleSequenceStep(/** @type {Partial<RuleSequenceStep>} */($$parsedSource));
    }
}

/**
 * RuleType defines the category of the detection rule.
 * @readonly
 * @enum {string}
 */
export const RuleType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * GraphRuleType is the RuleType constant for graph-aware rules.
     */
    GraphRuleType: "graph",

    ThresholdRule: "threshold",
    FrequencyRule: "frequency",
    SequenceRule: "sequence",
    CorrelationRule: "correlation",
};

/**
 * TimelineEvent represents a single point in an incident's progression.
 */
export class TimelineEvent {
    /**
     * Creates a new TimelineEvent instance.
     * @param {Partial<TimelineEvent>} [$$source = {}] - The source object to create the TimelineEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("type" in $$source)) {
            /**
             * "ALERT", "EVENT", "SYSTEM"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tactic"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["technique"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["severity"] = undefined;
        }
        if (!("entity_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entity_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * ID of the parent/triggering event
             * @member
             * @type {string | undefined}
             */
            this["causality_id"] = undefined;
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimelineEvent}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField10_0($$parsedSource["metadata"]);
        }
        return new TimelineEvent(/** @type {Partial<TimelineEvent>} */($$parsedSource));
    }
}

/**
 * ValidationResult holds the status of a rule's static analysis
 */
export class ValidationResult {
    /**
     * Creates a new ValidationResult instance.
     * @param {Partial<ValidationResult>} [$$source = {}] - The source object to create the ValidationResult.
     */
    constructor($$source = {}) {
        if (!("is_valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_valid"] = false;
        }
        if (!("rule_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rule_id"] = "";
        }
        if (!("rule_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rule_name"] = "";
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }
        if (!("is_secured" in $$source)) {
            /**
             * True if we confirmed malicious logic is absent
             * @member
             * @type {boolean}
             */
            this["is_secured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new ValidationResult(/** @type {Partial<ValidationResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = FusionAlertInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = TimelineEvent.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = Match.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Event.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = RuleSequenceStep.createFrom;
const $$createType13 = $Create.Array($$createType12);
